MINI-PROJETO DE VISUALIZAÇÃO E BUSINESS INTELLIGENCE

In [17]:
#Carregamento de bibliotecas para concatenacao de arquivos csv
import pandas as pd
import unicodedata
import warnings
warnings.filterwarnings('ignore')

print('Carreganto de biblioteca com sucesso')

Carreganto de biblioteca com sucesso

In [18]:
# ============================================
# SPRINT 2: Importar os arquivos anuais
# ============================================

# Lista de anos e nomes dos arquivos
anos = [2020, 2021, 2022, 2023, 2024, 2025, 2026]
arquivos = [f'{ano}.csv' for ano in anos]

# Dicionário para armazenar os DataFrames
dataframes = {}

# Loop para carregar cada arquivo
for ano, arquivo in zip(anos, arquivos):
    try:
        dataframes[ano] = pd.read_csv(arquivo, sep=';', encoding='utf-8')
        print(f"✅ {ano} carregado: {dataframes[ano].shape[0]:,} registros")
    except FileNotFoundError:
        print(f"❌ Arquivo {arquivo} não encontrado!")
        exit()

print("\n📌 Todos os arquivos foram carregados com sucesso!")

✅ 2020 carregado: 84,819 registros
✅ 2021 carregado: 83,622 registros
✅ 2022 carregado: 88,991 registros
✅ 2023 carregado: 31,992 registros
✅ 2024 carregado: 26,258 registros
✅ 2025 carregado: 26,215 registros
✅ 2026 carregado: 819 registros

📌 Todos os arquivos foram carregados com sucesso!

In [19]:
# ============================================
# ANÁLISE EXPLORATÓRIA DE DADOS (EDA) 
# ============================================

def explorar_dataframe(df, nome="DataFrame"):
    """
    Realiza uma análise exploratória básica em um DataFrame.
    Exibe: shape, colunas, dtypes, head, info, describe, nulos, duplicatas.
    """
    print("="*60)
    print(f"🔹 ANÁLISE EXPLORATÓRIA: {nome}")
    print("="*60)
    
    # 1. Shape (dimensões)
    print(f"\n📌 SHAPE: {df.shape[0]} linhas x {df.shape[1]} colunas")
    
    # 2. Colunas e tipos
    print("\n📌 COLUNAS E TIPOS:")
    print(df.dtypes.to_string())
    
    # 3. Primeiras linhas
    print("\n📌 HEAD (primeiras 5 linhas):")
    display(df.head())  # use print(df.head()) se não estiver no Jupyter
    
    # 4. Últimas linhas (opcional)
    print("\n📌 TAIL (últimas 5 linhas):")
    display(df.tail())
    
    # 5. Informações gerais (info)
    print("\n📌 INFO (resumo):")
    # Buffer para capturar a saída do info e exibir como string
    from io import StringIO
    buffer = StringIO()
    df.info(buf=buffer)
    print(buffer.getvalue())
    
    # 6. Estatísticas descritivas - numéricas
    print("\n📌 ESTATÍSTICAS DESCRITIVAS (numéricas):")
    display(df.describe())
    
    # 7. Estatísticas descritivas - categóricas
    cat_cols = df.select_dtypes(include=['object', 'category']).columns
    if len(cat_cols) > 0:
        print("\n📌 ESTATÍSTICAS DESCRITIVAS (categóricas):")
        display(df[cat_cols].describe())
    
    print("-"*60)



anos = [2020, 2021, 2022, 2023, 2024, 2025, 2026]

for ano in anos:
    if ano in dataframes:
        explorar_dataframe(dataframes[ano], f"Base {ano} (original)")
    else:
        print(f"⚠️ Ano {ano} não encontrado.")

============================================================
🔹 ANÁLISE EXPLORATÓRIA: Base 2020 (original)
============================================================

📌 SHAPE: 84819 linhas x 25 colunas

📌 COLUNAS E TIPOS:
ano_compra                           int64
nome_instituicao                       str
esfera                                 str
cnpj_instituicao                       str
municipio_instituicao                  str
uf                                     str
compra                                 str
insercao                               str
codigo_br                            int64
descricao_catmat                       str
unidade_fornecimento                   str
generico                               str
anvisa                             float64
modalidade_compra                      str
tipo_compra                            str
capacidade                         float64
unidade_medida                         str
unidade_fornecimento_capacidade        str
cnpj_fornecedor                        str
fornecedor                             str
cnpj_fabricante                        str
fabricante                             str
qtd_itens_comprados                  int64
preco_unitario                     float64
preco_total                        float64

📌 HEAD (primeiras 5 linhas):

,ano_compra,nome_instituicao,esfera,cnpj_instituicao,municipio_instituicao,uf,compra,insercao,codigo_br,descricao_catmat,...,capacidade,unidade_medida,unidade_fornecimento_capacidade,cnpj_fornecedor,fornecedor,cnpj_fabricante,fabricante,qtd_itens_comprados,preco_unitario,preco_total
0,2020,FUNDO MUNICIPAL DE SAUDE DE MARABA,MUNICIPAL,18.478.187/0001-07,MARABA,PA,01/01/2020,19/01/2024,270019,"GLICONATO DE CÁLCIO, DOSAGEM:10%, APRESENTAÇÃO...",...,10.0,ML,AMPOLA 10.00 ML,04.949.905/0001-63,F CARDOSO E CIA LTDA,01.571.702/0001-98,HALEX ISTAR INDUSTRIA FARMACEUTICA SA,9750,4.500,43875.0
1,2020,FUNDO MUNICIPAL DE SAUDE - MUNICIPIO DE ALTO P...,MUNICIPAL,08.533.932/0001-01,ALTO PARANA,PR,01/01/2020,13/03/2020,243488,"BOLSA VENTILAÇÃO PULMONAR, MATERIAL:BORRACHA, ...",...,NaN,NaN,UNIDADE,06.974.929/0001-06,NOROESTE MEDICAMENTOS LTDA,73.856.593/0001-66,"PRATI, DONADUZZI & CIA LTDA",3,6.900,20.7
2,2020,MUNICIPIO DE AMERICO BRASILIENSE,MUNICIPAL,43.976.166/0001-50,AMERICO BRASILIENSE,SP,01/01/2020,06/10/2020,267567,"CARVEDILOL, DOSAGEM:25 MG",...,NaN,NaN,COMPRIMIDO,01.140.868/0001-50,CIRURGICA OLIMPIO LTDA,61.150.447/0001-31,LABORATORIOS BALDACCI LTDA EM RECUPERACAO JUDI...,36000,0.155,5580.0
3,2020,MUNICIPIO DE AMERICO BRASILIENSE,MUNICIPAL,43.976.166/0001-50,AMERICO BRASILIENSE,SP,01/01/2020,06/10/2020,271356,"ALPRAZOLAM, DOSAGEM:1 MG",...,NaN,NaN,COMPRIMIDO,01.140.868/0001-50,CIRURGICA OLIMPIO LTDA,05.254.971/0001-81,ZYDUS NIKKHO FARMACEUTICA LTDA,240000,0.099,23760.0
4,2020,MUNICIPIO DE AMERICO BRASILIENSE,MUNICIPAL,43.976.166/0001-50,AMERICO BRASILIENSE,SP,01/01/2020,06/10/2020,267565,"CARVEDILOL, DOSAGEM:6,25 MG",...,NaN,NaN,COMPRIMIDO,01.140.868/0001-50,CIRURGICA OLIMPIO LTDA,61.150.447/0001-31,LABORATORIOS BALDACCI LTDA EM RECUPERACAO JUDI...,36000,0.086,3096.0

📌 TAIL (últimas 5 linhas):

,ano_compra,nome_instituicao,esfera,cnpj_instituicao,municipio_instituicao,uf,compra,insercao,codigo_br,descricao_catmat,...,capacidade,unidade_medida,unidade_fornecimento_capacidade,cnpj_fornecedor,fornecedor,cnpj_fabricante,fabricante,qtd_itens_comprados,preco_unitario,preco_total
84814,2020,SECRETARIA DE ESTADO DA SAUDE,ESTADUAL,46.374.500/0262-31,SAO PAULO,SP,30/12/2020,03/08/2021,342134,"HIDROCORTISONA, COMPOSIÇÃO:SAL SUCCINATO SÓDIC...",...,NaN,NaN,FRASCO-AMPOLA,67.729.178/0004-91,COMERCIAL CIRURGICA RIOCLARENSE LTDA,17.159.229/0001-76,LABORATORIO TEUTO BRASILEIRO S/A,272190,4.0000,1088760.0
84815,2020,MUNICIPIO DE SALTO,MUNICIPAL,46.634.507/0001-06,SALTO,SP,30/12/2020,16/08/2021,267613,"CAPTOPRIL, CONCENTRAÇÃO:25 MG",...,NaN,NaN,COMPRIMIDO,05.847.630/0001-10,SOMA/SP PRODUTOS HOSPITALARES LTDA,03.485.572/0001-04,GEOLAB INDUSTRIA FARMACEUTICA S/A,96000,0.0308,2956.8
84816,2020,MUNICIPIO DE SALTO,MUNICIPAL,46.634.507/0001-06,SALTO,SP,30/12/2020,16/08/2021,267662,"FLUCONAZOL, DOSAGEM:150 MG",...,NaN,NaN,CÁPSULA,05.847.630/0001-10,SOMA/SP PRODUTOS HOSPITALARES LTDA,17.875.154/0001-20,MEDQUIMICA INDUSTRIA FARMACEUTICA LTDA.,1800,0.4200,756.0
84817,2020,FUNDO MUNICIPAL DE SAUDE DE CASCAVEL,MUNICIPAL,09.051.532/0001-22,CASCAVEL,PR,31/12/2020,17/02/2021,278489,"ÁCIDO FÓLICO, DOSAGEM:0,2 MG/ML, USO:SOLUÇÃO O...",...,30.0,ML,FRASCO 30.00 ML,81.706.251/0001-98,PROMEFARMA MEDICAMENTOS E PRODUTOS HOSPITALARE...,02.456.955/0001-83,NATULAB LABORATORIO S.A,800,4.7490,3799.2
84818,2020,SECRETARIA DE ESTADO DA SAUDE,ESTADUAL,46.374.500/0262-31,SAO PAULO,SP,31/12/2020,03/08/2021,269843,"LIDOCAÍNA CLORIDRATO, DOSAGEM:2%, APRESENTAÇÃO...",...,20.0,ML,FRASCO 20.00 ML,67.729.178/0004-91,COMERCIAL CIRURGICA RIOCLARENSE LTDA,17.174.657/0001-78,HYPOFARMA INSTITUTO DE HYPODERMIA E FARMACIA LTDA,403830,2.5000,1009575.0

📌 INFO (resumo):
<class 'pandas.DataFrame'>
RangeIndex: 84819 entries, 0 to 84818
Data columns (total 25 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   ano_compra                       84819 non-null  int64
 1   nome_instituicao                 84819 non-null  str
 2   esfera                           84819 non-null  str
 3   cnpj_instituicao                 84819 non-null  str
 4   municipio_instituicao            84819 non-null  str
 5   uf                               84819 non-null  str
 6   compra                           84819 non-null  str
 7   insercao                         84819 non-null  str
 8   codigo_br                        84819 non-null  int64
 9   descricao_catmat                 84819 non-null  str
 10  unidade_fornecimento             84813 non-null  str
 11  generico                         37135 non-null  str
 12  anvisa                           37135 non-null  float64
 13  modalidade_compra                84819 non-null  str
 14  tipo_compra                      84819 non-null  str
 15  capacidade                       31382 non-null  float64
 16  unidade_medida                   31382 non-null  str
 17  unidade_fornecimento_capacidade  84813 non-null  str
 18  cnpj_fornecedor                  84819 non-null  str
 19  fornecedor                       84819 non-null  str
 20  cnpj_fabricante                  84819 non-null  str
 21  fabricante                       84819 non-null  str
 22  qtd_itens_comprados              84819 non-null  int64
 23  preco_unitario                   84819 non-null  float64
 24  preco_total                      84819 non-null  float64
dtypes: float64(4), int64(3), str(18)
memory usage: 16.2 MB


📌 ESTATÍSTICAS DESCRITIVAS (numéricas):

,ano_compra,codigo_br,anvisa,capacidade,qtd_itens_comprados,preco_unitario,preco_total
count,84819.0,84819.000000,3.713500e+04,31382.000000,8.481900e+04,84819.000000,8.481900e+04
mean,2020.0,321480.766173,1.178232e+12,78.803936,1.033890e+05,72.659431,5.950040e+04
std,0.0,70195.757392,1.984979e+11,220.446568,2.258634e+06,2295.104827,2.525328e+06
min,2020.0,209754.000000,1.002900e+12,0.050000,1.000000e+00,0.000100,1.000000e-04
25%,2020.0,268252.000000,1.036702e+12,3.000000,2.000000e+02,0.320000,5.565000e+02
50%,2020.0,273400.000000,1.071402e+12,20.000000,1.400000e+03,1.500000,2.160000e+03
75%,2020.0,394103.000000,1.256802e+12,100.000000,1.000000e+04,6.020000,9.000000e+03
max,2020.0,604961.000000,1.986000e+12,5000.000000,4.876200e+08,255614.900000,6.216000e+08

📌 ESTATÍSTICAS DESCRITIVAS (categóricas):

,nome_instituicao,esfera,cnpj_instituicao,municipio_instituicao,uf,compra,insercao,descricao_catmat,unidade_fornecimento,generico,modalidade_compra,tipo_compra,unidade_medida,unidade_fornecimento_capacidade,cnpj_fornecedor,fornecedor,cnpj_fabricante,fabricante
count,84819,84819,84819,84819,84819,84819,84819,84819,84813,37135,84819,84819,31382,84813,84819,84819,84819,84819
unique,383,3,482,454,22,312,660,7350,40,2,9,1,12,256,1543,1478,1493,1367
top,FUNDO MUNICIPAL DE SAUDE,MUNICIPAL,12.075.748/0001-32,FLORIANOPOLIS,PR,15/05/2020,10/08/2020,"CLORETO DE SÓDIO, PRINCÍPIO ATIVO:0,9%_ SOLUÇÃ...",COMPRIMIDO,S,Pregão,ADMINISTRATIVA,ML,COMPRIMIDO,12.889.035/0001-02,INOVAMED HOSPITALAR LTDA,73.856.593/0001-66,"PRATI, DONADUZZI & CIA LTDA"
freq,15921,81535,1410,1550,23883,1524,1440,349,30322,22055,80358,84819,25543,30322,2424,2424,6044,6156

------------------------------------------------------------
============================================================
🔹 ANÁLISE EXPLORATÓRIA: Base 2021 (original)
============================================================

📌 SHAPE: 83622 linhas x 25 colunas

📌 COLUNAS E TIPOS:
ano_compra                           int64
nome_instituicao                       str
esfera                                 str
cnpj_instituicao                       str
municipio_instituicao                  str
uf                                     str
compra                                 str
insercao                               str
codigo_br                            int64
descricao_catmat                       str
unidade_fornecimento                   str
generico                               str
anvisa                             float64
modalidade_compra                      str
tipo_compra                            str
capacidade                         float64
unidade_medida                         str
unidade_fornecimento_capacidade        str
cnpj_fornecedor                        str
fornecedor                             str
cnpj_fabricante                        str
fabricante                             str
qtd_itens_comprados                  int64
preco_unitario                     float64
preco_total                        float64

📌 HEAD (primeiras 5 linhas):

,ano_compra,nome_instituicao,esfera,cnpj_instituicao,municipio_instituicao,uf,compra,insercao,codigo_br,descricao_catmat,...,capacidade,unidade_medida,unidade_fornecimento_capacidade,cnpj_fornecedor,fornecedor,cnpj_fabricante,fabricante,qtd_itens_comprados,preco_unitario,preco_total
0,2021,FUNDO MUNICIPAL DE SAUDE DE MARABA,MUNICIPAL,18.478.187/0001-07,MARABA,PA,01/01/2021,29/12/2023,475706,"BOLSA OSTOMIA, MATÉRIA PRIMA:PLáSTICO, APLICAÇ...",...,NaN,NaN,UNIDADE,00.890.752/0001-75,BRIUTE COMERCIO DE PRODUTOS E EQUIPAMENTOS HOS...,02.794.555/0003-40,COLOPLAST DO BRASIL LTDA,5000,18.79,93950.0
1,2021,FUNDO MUNICIPAL DE SAUDE - MUNICIPIO DE ARIRAN...,MUNICIPAL,09.380.391/0001-91,ARIRANHA DO IVAI,PR,01/01/2021,13/04/2021,268505,"ONDANSETRONA CLORIDRATO, DOSAGEM:8 MG",...,NaN,NaN,COMPRIMIDO,04.880.586/0001-87,CIRURGICA REAL - COMERCIAL HOSPITALAR E FARMAC...,58.430.828/0013-01,BLAU FARMACEUTICA S.A.,5000,1.83,9150.0
2,2021,FUNDO MUNICIPAL DE SAUDE DE MARABA,MUNICIPAL,18.478.187/0001-07,MARABA,PA,01/01/2021,27/12/2023,443023,"ARTIGO PARA HIGIENE NO LEITO, TIPO:LUVA, MATER...",...,NaN,NaN,UNIDADE,10.468.162/0001-02,FARMACEUTICA DISTRIBUIDORA LTDA,04.214.934/0001-87,SUPERMAX BRASIL IMPORTADORA S/A,900,39.00,35100.0
3,2021,FUNDO MUNICIPAL DE SAUDE - MUNICIPIO DE ARIRAN...,MUNICIPAL,09.380.391/0001-91,ARIRANHA DO IVAI,PR,01/01/2021,13/04/2021,269843,"LIDOCAÍNA CLORIDRATO, DOSAGEM:2%, APRESENTAÇÃO...",...,20.0,ML,FRASCO 20.00 ML,04.880.586/0001-87,CIRURGICA REAL - COMERCIAL HOSPITALAR E FARMAC...,19.570.720/0003-82,HIPOLABOR FARMACEUTICA LTDA,50,2.64,132.0
4,2021,FUNDO MUNICIPAL DE SAUDE DE MARABA,MUNICIPAL,18.478.187/0001-07,MARABA,PA,01/01/2021,27/12/2023,438840,"CATETER P/ INTERVENÇÃO, TIPO DE CATETER:PARA T...",...,NaN,NaN,UNIDADE,10.468.162/0001-02,FARMACEUTICA DISTRIBUIDORA LTDA,01.005.728/0001-79,LABOR IMPORT COMERCIAL IMPORTADORA EXPORTADORA...,3000,1.03,3090.0

📌 TAIL (últimas 5 linhas):

,ano_compra,nome_instituicao,esfera,cnpj_instituicao,municipio_instituicao,uf,compra,insercao,codigo_br,descricao_catmat,...,capacidade,unidade_medida,unidade_fornecimento_capacidade,cnpj_fornecedor,fornecedor,cnpj_fabricante,fabricante,qtd_itens_comprados,preco_unitario,preco_total
83617,2021,FUNDO MUNICIPAL DE SAUDE,MUNICIPAL,07.851.282/0001-80,ROLIM DE MOURA,RO,31/12/2021,11/01/2022,292194,"HALOPERIDOL, APRESENTAÇÃO:SAL DECANOATO, CONCE...",...,1.0,ML,AMPOLA 1.00 ML,17.472.278/0001-64,GOLDENPLUS - COMERCIO DE MEDICAMENTOS E PRODUT...,44.734.671/0001-51,CRISTALIA PRODUTOS QUIMICOS FARMACEUTICOS LTDA,7500,10.96,82200.0
83618,2021,FUNDO MUNICIPAL DE SAUDE,MUNICIPAL,07.851.282/0001-80,ROLIM DE MOURA,RO,31/12/2021,11/01/2022,292418,"CIPROFLOXACINO CLORIDRATO, DOSAGEM:2 MG/ML, AP...",...,200.0,ML,FRASCO 200.00 ML,34.620.735/0001-30,GHOLDMED DISTRIBUIDORA DE PRODUTOS HOSPITALARE...,02.281.006/0001-00,ISOFARMA INDUSTRIAL FARMACEUTICA LTDA,1500,51.00,76500.0
83619,2021,FUNDO MUNICIPAL DE SAUDE,MUNICIPAL,07.851.282/0001-80,ROLIM DE MOURA,RO,31/12/2021,11/01/2022,292419,"CLINDAMICINA, DOSAGEM:150 MG/ML, APRESENTAÇÃO:...",...,2.0,ML,AMPOLA 2.00 ML,05.443.348/0001-77,CENTERMEDICA PRODUTOS HOSPITALARES LTDA,17.174.657/0001-78,HYPOFARMA INSTITUTO DE HYPODERMIA E FARMACIA LTDA,800,9.00,7200.0
83620,2021,FUNDO MUNICIPAL DE SAUDE,MUNICIPAL,07.851.282/0001-80,ROLIM DE MOURA,RO,31/12/2021,11/01/2022,292418,"CIPROFLOXACINO CLORIDRATO, DOSAGEM:2 MG/ML, AP...",...,100.0,ML,BOLSA 100.00 ML,33.688.692/0001-61,DISMART DISTRIBUIDORA HOSPITALAR LTDA,17.174.657/0001-78,HYPOFARMA INSTITUTO DE HYPODERMIA E FARMACIA LTDA,1000,24.84,24840.0
83621,2021,FUNDO MUNICIPAL DE SAUDE,MUNICIPAL,07.851.282/0001-80,ROLIM DE MOURA,RO,31/12/2021,11/01/2022,272329,"PETIDINA CLORIDRATO, DOSAGEM:50 MG/ML, APRESEN...",...,2.0,ML,AMPOLA 2.00 ML,34.620.735/0001-30,GHOLDMED DISTRIBUIDORA DE PRODUTOS HOSPITALARE...,60.665.981/0009-75,UNIAO QUIMICA FARMACEUTICA NACIONAL S A,500,6.81,3405.0

📌 INFO (resumo):
<class 'pandas.DataFrame'>
RangeIndex: 83622 entries, 0 to 83621
Data columns (total 25 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   ano_compra                       83622 non-null  int64
 1   nome_instituicao                 83614 non-null  str
 2   esfera                           83622 non-null  str
 3   cnpj_instituicao                 83622 non-null  str
 4   municipio_instituicao            83622 non-null  str
 5   uf                               83622 non-null  str
 6   compra                           83622 non-null  str
 7   insercao                         83622 non-null  str
 8   codigo_br                        83622 non-null  int64
 9   descricao_catmat                 83622 non-null  str
 10  unidade_fornecimento             83618 non-null  str
 11  generico                         38423 non-null  str
 12  anvisa                           38423 non-null  float64
 13  modalidade_compra                83622 non-null  str
 14  tipo_compra                      83622 non-null  str
 15  capacidade                       30221 non-null  float64
 16  unidade_medida                   30221 non-null  str
 17  unidade_fornecimento_capacidade  83618 non-null  str
 18  cnpj_fornecedor                  83622 non-null  str
 19  fornecedor                       83622 non-null  str
 20  cnpj_fabricante                  83622 non-null  str
 21  fabricante                       83622 non-null  str
 22  qtd_itens_comprados              83622 non-null  int64
 23  preco_unitario                   83622 non-null  float64
 24  preco_total                      83622 non-null  float64
dtypes: float64(4), int64(3), str(18)
memory usage: 15.9 MB


📌 ESTATÍSTICAS DESCRITIVAS (numéricas):

,ano_compra,codigo_br,anvisa,capacidade,qtd_itens_comprados,preco_unitario,preco_total
count,83622.0,83622.000000,3.842300e+04,30221.000000,8.362200e+04,83622.000000,8.362200e+04
mean,2021.0,324170.393318,1.193591e+12,79.326242,1.278338e+05,62.759711,8.862627e+04
std,0.0,72452.265802,2.110751e+11,209.261933,2.467558e+06,1757.946182,2.460523e+06
min,2021.0,209754.000000,1.002900e+12,0.200000,1.000000e+00,0.000100,1.000000e-04
25%,2021.0,268277.000000,1.037001e+12,4.000000,2.500000e+02,0.350000,6.587550e+02
50%,2021.0,273710.000000,1.097403e+12,20.000000,1.500000e+03,1.740000,2.520000e+03
75%,2021.0,396471.000000,1.256803e+12,100.000000,1.000000e+04,6.740000,1.112400e+04
max,2021.0,631739.000000,1.986000e+12,5000.000000,4.876200e+08,266097.600000,4.845120e+08

📌 ESTATÍSTICAS DESCRITIVAS (categóricas):

,nome_instituicao,esfera,cnpj_instituicao,municipio_instituicao,uf,compra,insercao,descricao_catmat,unidade_fornecimento,generico,modalidade_compra,tipo_compra,unidade_medida,unidade_fornecimento_capacidade,cnpj_fornecedor,fornecedor,cnpj_fabricante,fabricante
count,83614,83622,83622,83622,83622,83622,83622,83622,83618,38423,83622,83622,30221,83618,83622,83622,83622,83622
unique,378,3,475,442,22,324,662,7460,40,2,8,2,13,264,1623,1528,1500,1362
top,FUNDO MUNICIPAL DE SAUDE,MUNICIPAL,12.075.748/0001-32,FLORIANOPOLIS,PR,07/05/2021,19/08/2021,"CLORETO DE SÓDIO, PRINCÍPIO ATIVO:0,9%_ SOLUÇÃ...",COMPRIMIDO,S,Pregão,ADMINISTRATIVA,ML,COMPRIMIDO,81.706.251/0001-98,PROMEFARMA MEDICAMENTOS E PRODUTOS HOSPITALARE...,73.856.593/0001-66,"PRATI, DONADUZZI & CIA LTDA"
freq,16624,79684,1489,1722,20320,1993,1257,414,29893,22140,78885,83618,24409,29893,1905,1905,5823,5873

------------------------------------------------------------
============================================================
🔹 ANÁLISE EXPLORATÓRIA: Base 2022 (original)
============================================================

📌 SHAPE: 88991 linhas x 25 colunas

📌 COLUNAS E TIPOS:
ano_compra                           int64
nome_instituicao                       str
esfera                                 str
cnpj_instituicao                       str
municipio_instituicao                  str
uf                                     str
compra                                 str
insercao                               str
codigo_br                            int64
descricao_catmat                       str
unidade_fornecimento                   str
generico                               str
anvisa                             float64
modalidade_compra                      str
tipo_compra                            str
capacidade                         float64
unidade_medida                         str
unidade_fornecimento_capacidade        str
cnpj_fornecedor                        str
fornecedor                             str
cnpj_fabricante                        str
fabricante                             str
qtd_itens_comprados                  int64
preco_unitario                     float64
preco_total                        float64

📌 HEAD (primeiras 5 linhas):

,ano_compra,nome_instituicao,esfera,cnpj_instituicao,municipio_instituicao,uf,compra,insercao,codigo_br,descricao_catmat,...,capacidade,unidade_medida,unidade_fornecimento_capacidade,cnpj_fornecedor,fornecedor,cnpj_fabricante,fabricante,qtd_itens_comprados,preco_unitario,preco_total
0,2022,FUNDO MUNICIPAL DE SAUDE DE MARABA,MUNICIPAL,18.478.187/0001-07,MARABA,PA,01/01/2022,23/01/2024,394088,"BICARBONATO DE SÓDIO, CONCENTRAÇÃO:8,40%, FORM...",...,250.0,ML,FRASCO 250.00 ML,24.626.549/0001-54,INSTRUMED INSTRUMENTOS MEDICOS HOSPITALARES LTDA,17.174.657/0008-44,HYPOFARMA INSTITUTO DE HYPODERMIA E FARMACIA LTDA,300,22.060,6618.00
1,2022,FUNDO MUNICIPAL DE SAUDE DE MARABA,MUNICIPAL,18.478.187/0001-07,MARABA,PA,01/01/2022,15/02/2024,437587,"EPINEFRINA, CONCENTRAÇÃO:0,5 MG/ML, FORMA FARM...",...,NaN,NaN,DOSE,20.918.668/0001-20,MEDICINALI PRODUTOS PARA SAUDE LTDA,58.430.828/0001-60,BLAU FARMACEUTICA S.A.,24,5.850,140.40
2,2022,FUNDO MUNICIPAL DE SAUDE DE MARABA,MUNICIPAL,18.478.187/0001-07,MARABA,PA,01/01/2022,23/01/2024,371273,"CLORETO DE SÓDIO, CONCENTRAÇAO:0,9 %, FORMA FA...",...,250.0,ML,FRASCO 250.00 ML,24.626.549/0001-54,INSTRUMED INSTRUMENTOS MEDICOS HOSPITALARES LTDA,06.628.333/0001-46,FARMACE - INDUSTRIA QUIMICO-FARMACEUTICA CEARE...,3750,7.000,26250.00
3,2022,FUNDO MUNICIPAL DE SAUDE DE MARABA,MUNICIPAL,18.478.187/0001-07,MARABA,PA,01/01/2022,06/02/2024,391582,"CONDICIONADOR DENTAL, TIPO:ÁCIDO FOSFÓRICO, CO...",...,NaN,NaN,SERINGA,36.028.477/0001-22,HIPERFAR MATERIAIS HOSPITALAR E MEDICAMENTOS LTDA,97.215.388/0001-80,LEONARDI COMERCIO DE PRODUTOS PARA SAUDE LTDA,30,9.555,286.65
4,2022,FUNDO MUNICIPAL DE SAUDE DE MARABA,MUNICIPAL,18.478.187/0001-07,MARABA,PA,01/01/2022,23/01/2024,358753,"MISOPROSTOL, CONCENTRAÇAO:25 MCG, FORMA FARMAC...",...,NaN,NaN,COMPRIMIDO,34.875.727/0001-34,LOBATO COMERCIO DE PRODUTOS HOSPITALARES LTDA,08.939.548/0001-03,INFAN INDUSTRIA QUIMICA FARMACEUTICA NACIONAL S/A,3000,11.400,34200.00

📌 TAIL (últimas 5 linhas):

,ano_compra,nome_instituicao,esfera,cnpj_instituicao,municipio_instituicao,uf,compra,insercao,codigo_br,descricao_catmat,...,capacidade,unidade_medida,unidade_fornecimento_capacidade,cnpj_fornecedor,fornecedor,cnpj_fabricante,fabricante,qtd_itens_comprados,preco_unitario,preco_total
88986,2022,FUNDO MUNICIPAL DE SAUDE,MUNICIPAL,11.095.923/0001-90,INOCENCIA,MS,30/12/2022,23/01/2023,392708,"METFORMINA CLORIDRATO, COMPOSIÇÃO:ASSOCIADA À ...",...,NaN,NaN,COMPRIMIDO,10.749.758/0001-80,A.D. DAMINELLI LTDA,33.069.212/0001-84,MERCK S/A,4320,3.95,17064.0
88987,2022,FUNDO MUNICIPAL DE SAUDE,MUNICIPAL,11.095.923/0001-90,INOCENCIA,MS,30/12/2022,23/01/2023,390005,"QUETIAPINA, CONCENTRAÇÃO:50 MG, FORMA FARMACÊU...",...,NaN,NaN,COMPRIMIDO,10.749.758/0001-80,A.D. DAMINELLI LTDA,61.190.096/0001-92,EUROFARMA LABORATORIOS S.A.,2200,2.46,5412.0
88988,2022,FUNDO MUNICIPAL DE SAUDE,MUNICIPAL,11.095.923/0001-90,INOCENCIA,MS,30/12/2022,23/01/2023,268214,"ATROPINA SULFATO, DOSAGEM:0,25 MG/ML, USO:SOLU...",...,1.0,ML,AMPOLA 1.00 ML,36.121.635/0001-94,CG HOSPITALAR DISTRIBUIDORA DE PRODUTOS HOSPIT...,06.628.333/0001-46,FARMACE - INDUSTRIA QUIMICO-FARMACEUTICA CEARE...,1200,6.34,7608.0
88989,2022,FUNDO MUNICIPAL DE SAUDE,MUNICIPAL,11.095.923/0001-90,INOCENCIA,MS,30/12/2022,23/01/2023,396471,"FENOTEROL BROMIDRATO, CONCENTRAÇÃO:5 MG/ML, FO...",...,20.0,ML,FRASCO 20.00 ML,10.566.711/0001-81,DIFE DISTRIBUIDORA DE MEDICAMENTOS LTDA,17.174.657/0001-78,HYPOFARMA INSTITUTO DE HYPODERMIA E FARMACIA LTDA,120,14.40,1728.0
88990,2022,FUNDO MUNICIPAL DE SAUDE,MUNICIPAL,11.095.923/0001-90,INOCENCIA,MS,30/12/2022,23/01/2023,401890,"CIANOCOBALAMINA, COMPOSIÇÃO:ASSOCIADA COM PIRI...",...,1.0,ML,AMPOLA 1.00 ML,81.706.251/0001-98,PROMEFARMA MEDICAMENTOS E PRODUTOS HOSPITALARE...,07.670.111/0001-54,ARESE PHARMA LTDA.,400,11.17,4468.0

📌 INFO (resumo):
<class 'pandas.DataFrame'>
RangeIndex: 88991 entries, 0 to 88990
Data columns (total 25 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   ano_compra                       88991 non-null  int64
 1   nome_instituicao                 88991 non-null  str
 2   esfera                           88991 non-null  str
 3   cnpj_instituicao                 88991 non-null  str
 4   municipio_instituicao            88991 non-null  str
 5   uf                               88991 non-null  str
 6   compra                           88991 non-null  str
 7   insercao                         88871 non-null  str
 8   codigo_br                        88991 non-null  int64
 9   descricao_catmat                 88991 non-null  str
 10  unidade_fornecimento             88987 non-null  str
 11  generico                         39978 non-null  str
 12  anvisa                           39978 non-null  float64
 13  modalidade_compra                88991 non-null  str
 14  tipo_compra                      88991 non-null  str
 15  capacidade                       31346 non-null  float64
 16  unidade_medida                   31346 non-null  str
 17  unidade_fornecimento_capacidade  88987 non-null  str
 18  cnpj_fornecedor                  88991 non-null  str
 19  fornecedor                       88991 non-null  str
 20  cnpj_fabricante                  88991 non-null  str
 21  fabricante                       88991 non-null  str
 22  qtd_itens_comprados              88991 non-null  int64
 23  preco_unitario                   88991 non-null  float64
 24  preco_total                      88991 non-null  float64
dtypes: float64(4), int64(3), str(18)
memory usage: 17.0 MB


📌 ESTATÍSTICAS DESCRITIVAS (numéricas):

,ano_compra,codigo_br,anvisa,capacidade,qtd_itens_comprados,preco_unitario,preco_total
count,88991.0,88991.000000,3.997800e+04,31346.000000,8.899100e+04,88991.000000,8.899100e+04
mean,2022.0,329404.950546,1.194319e+12,76.550523,1.706506e+05,103.163035,1.895063e+05
std,0.0,75578.922353,2.136779e+11,209.997785,4.979793e+06,3109.617821,4.529636e+06
min,2022.0,209754.000000,1.002900e+12,0.200000,1.000000e+00,0.000100,1.000000e-04
25%,2022.0,268422.000000,1.031101e+12,3.000000,2.500000e+02,0.380000,7.500000e+02
50%,2022.0,276378.000000,1.108500e+12,15.000000,1.620000e+03,2.120000,3.000000e+03
75%,2022.0,405671.000000,1.256803e+12,100.000000,1.200000e+04,8.000000,1.360000e+04
max,2022.0,631778.000000,1.986000e+12,5000.000000,8.196000e+08,495000.000000,6.765249e+08

📌 ESTATÍSTICAS DESCRITIVAS (categóricas):

,nome_instituicao,esfera,cnpj_instituicao,municipio_instituicao,uf,compra,insercao,descricao_catmat,unidade_fornecimento,generico,modalidade_compra,tipo_compra,unidade_medida,unidade_fornecimento_capacidade,cnpj_fornecedor,fornecedor,cnpj_fabricante,fabricante
count,88991,88991,88991,88991,88991,88991,88871,88991,88987,39978,88991,88991,31346,88987,88991,88991,88991,88991
unique,333,3,416,387,22,329,623,8449,42,2,8,2,12,285,1760,1661,1338,1221
top,FUNDO MUNICIPAL DE SAUDE,MUNICIPAL,12.075.748/0001-32,CURITIBA,PR,11/05/2022,16/11/2022,"CLORETO DE SÓDIO, PRINCÍPIO ATIVO:0,9%_ SOLUÇÃ...",COMPRIMIDO,S,Pregão,ADMINISTRATIVA,ML,COMPRIMIDO,44.734.671/0001-51,CRISTALIA PRODUTOS QUIMICOS FARMACEUTICOS LTDA,73.856.593/0001-66,"PRATI, DONADUZZI & CIA LTDA"
freq,16721,82219,1664,1812,19567,1788,1384,393,31391,21019,83982,88979,25250,31391,2088,2300,5568,5569

------------------------------------------------------------
============================================================
🔹 ANÁLISE EXPLORATÓRIA: Base 2023 (original)
============================================================

📌 SHAPE: 31992 linhas x 25 colunas

📌 COLUNAS E TIPOS:
ano_compra                           int64
nome_instituicao                       str
esfera                                 str
cnpj_instituicao                       str
municipio_instituicao                  str
uf                                     str
compra                                 str
insercao                               str
codigo_br                            int64
descricao_catmat                       str
unidade_fornecimento                   str
generico                               str
anvisa                             float64
modalidade_compra                      str
tipo_compra                            str
capacidade                         float64
unidade_medida                         str
unidade_fornecimento_capacidade        str
cnpj_fornecedor                        str
fornecedor                             str
cnpj_fabricante                        str
fabricante                             str
qtd_itens_comprados                  int64
preco_unitario                     float64
preco_total                        float64

📌 HEAD (primeiras 5 linhas):

,ano_compra,nome_instituicao,esfera,cnpj_instituicao,municipio_instituicao,uf,compra,insercao,codigo_br,descricao_catmat,...,capacidade,unidade_medida,unidade_fornecimento_capacidade,cnpj_fornecedor,fornecedor,cnpj_fabricante,fabricante,qtd_itens_comprados,preco_unitario,preco_total
0,2023,FUNDO MUNICIPAL DE SAUDE DE MARABA,MUNICIPAL,18.478.187/0001-07,MARABA,PA,01/01/2023,15/03/2024,423975,"PIPETA, TIPO:PASTEUR, CAPACIDADE:3 ML, MATERIA...",...,NaN,NaN,UNIDADE,05.323.167/0001-07,CIRUBEL COMERCIO E REPRESENTACOES DE PRODUTOS ...,57.893.521/0001-32,PERFITECNICA PERFIS TECNICOS DE BORRACHA LTDA,36,45.00,1620.0
1,2023,FUNDO MUNICIPAL DE SAUDE DE MARABA,MUNICIPAL,18.478.187/0001-07,MARABA,PA,01/01/2023,15/03/2024,457503,"CORANTE, TIPO :PARDO DE BISMARCK, CARACTERÍSTI...",...,NaN,NaN,UNIDADE,07.944.100/0001-15,PROC9 INDUSTRIA QUIMICA LTDA,07.944.100/0001-15,PROC9 INDUSTRIA QUIMICA LTDA,4,190.00,760.0
2,2023,FUNDO MUNICIPAL DE SAUDE DE MARABA,MUNICIPAL,18.478.187/0001-07,MARABA,PA,01/01/2023,15/03/2024,382447,"REAGENTE PARA DIAGNÓSTICO CLÍNICO 5, TIPO:ALBU...",...,10.0,ML,FRASCO 10.00 ML,05.048.534/0001-01,NORTEMED DISTRIBUIDORA DE PRODUTOS MEDICOS LTDA,50.657.402/0001-31,EBRAM PRODUTOS LABORATORIAIS LTDA,20,33.38,667.6
3,2023,FUNDO MUNICIPAL DE SAUDE DE MARABA,MUNICIPAL,18.478.187/0001-07,MARABA,PA,01/01/2023,15/03/2024,470305,"MEIO DE CULTURA - CÉLULA E TECIDO, TIPO:MEIO H...",...,NaN,NaN,GRAMA,05.323.167/0001-07,CIRUBEL COMERCIO E REPRESENTACOES DE PRODUTOS ...,73.636.391/0001-09,NEWPROV PRODUTOS PARA LABORATORIO LTDA,80,25.00,2000.0
4,2023,FUNDO MUNICIPAL DE SAUDE DE MARABA,MUNICIPAL,18.478.187/0001-07,MARABA,PA,01/01/2023,15/03/2024,479641,"ADAPTADOR USO MÉDICO, APLICAÇÃO:P/ AGULHA DE C...",...,NaN,NaN,UNIDADE,05.048.534/0001-01,NORTEMED DISTRIBUIDORA DE PRODUTOS MEDICOS LTDA,48.740.849/0001-28,CRAL ARTIGOS PARA LABORATORIO LTDA,50,38.71,1935.5

📌 TAIL (últimas 5 linhas):

,ano_compra,nome_instituicao,esfera,cnpj_instituicao,municipio_instituicao,uf,compra,insercao,codigo_br,descricao_catmat,...,capacidade,unidade_medida,unidade_fornecimento_capacidade,cnpj_fornecedor,fornecedor,cnpj_fabricante,fabricante,qtd_itens_comprados,preco_unitario,preco_total
31987,2023,MUNICIPIO DE UBERABA,MUNICIPAL,18.428.839/0001-90,UBERABA,MG,29/12/2023,05/06/2025,405899,"DESVENLAFAXINA, COMPOSIÇÃO:SAL SUCCINATO, CONC...",...,NaN,NaN,COMPRIMIDO,04.234.179/0001-00,DISTRIBEN DISTRIBUIDORA DE PRODUTOS FARMACEUTI...,60.659.463/0029-92,ACHE LABORATORIOS FARMACEUTICOS SA,1080,4.300,4644.00
31988,2023,MUNICIPIO DE UBERABA,MUNICIPAL,18.428.839/0001-90,UBERABA,MG,29/12/2023,05/06/2025,432637,"CRIZOTINIBE, CONCENTRAÇÃO :250 MG",...,NaN,NaN,CÁPSULA,47.271.160/0001-39,FAST PHARMA DISTRIBUIDORA E IMPORTADORA DE MED...,46.070.868/0001-69,LABORATORIOS PFIZER LTDA,720,417.753,300782.16
31989,2023,FUNDO MUNICIPAL DE SAUDE,MUNICIPAL,11.718.406/0001-20,ARACAJU,SE,29/12/2023,NaN,465751,"DIETA INFANTIL, INDICAÇÃO:A PARTIR 3 ANOS, ASP...",...,NaN,NaN,GRAMA,05.893.097/0001-22,CENUT - CENTRO ESPECIALIZADO DE NUTRICAO LTDA,23.643.315/0115-10,DANONE LTDA,42,250.650,10527.30
31990,2023,MUNICIPIO DE UBERABA,MUNICIPAL,18.428.839/0001-90,UBERABA,MG,29/12/2023,05/06/2025,433279,"DIVALPROATO DE SÓDIO, CONCENTRAÇÃO:250 MG, FOR...",...,NaN,NaN,COMPRIMIDO,04.234.179/0001-00,DISTRIBEN DISTRIBUIDORA DE PRODUTOS FARMACEUTI...,56.998.701/0001-16,ABBOTT LABORATORIOS DO BRASIL LTDA,6210,2.450,15214.50
31991,2023,NaN,MUNICIPAL,06.205.888/0001-85,SOBRADINHO,RS,30/12/2023,NaN,327566,"ÁCIDO TRANEXÂMICO, DOSAGEM:50 MG/ML, FORMA FAR...",...,5.0,ML,AMPOLA 5.00 ML,12.889.035/0001-02,INOVAMED HOSPITALAR LTDA,05.254.971/0001-81,ZYDUS NIKKHO FARMACEUTICA LTDA,200,4.099,819.80

📌 INFO (resumo):
<class 'pandas.DataFrame'>
RangeIndex: 31992 entries, 0 to 31991
Data columns (total 25 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   ano_compra                       31992 non-null  int64
 1   nome_instituicao                 31979 non-null  str
 2   esfera                           31992 non-null  str
 3   cnpj_instituicao                 31992 non-null  str
 4   municipio_instituicao            31992 non-null  str
 5   uf                               31992 non-null  str
 6   compra                           31992 non-null  str
 7   insercao                         31276 non-null  str
 8   codigo_br                        31992 non-null  int64
 9   descricao_catmat                 31992 non-null  str
 10  unidade_fornecimento             31992 non-null  str
 11  generico                         17405 non-null  str
 12  anvisa                           17405 non-null  float64
 13  modalidade_compra                31992 non-null  str
 14  tipo_compra                      31992 non-null  str
 15  capacidade                       12171 non-null  float64
 16  unidade_medida                   12171 non-null  str
 17  unidade_fornecimento_capacidade  31992 non-null  str
 18  cnpj_fornecedor                  31992 non-null  str
 19  fornecedor                       31992 non-null  str
 20  cnpj_fabricante                  31992 non-null  str
 21  fabricante                       31992 non-null  str
 22  qtd_itens_comprados              31992 non-null  int64
 23  preco_unitario                   31992 non-null  float64
 24  preco_total                      31992 non-null  float64
dtypes: float64(4), int64(3), str(18)
memory usage: 6.1 MB


📌 ESTATÍSTICAS DESCRITIVAS (numéricas):

,ano_compra,codigo_br,anvisa,capacidade,qtd_itens_comprados,preco_unitario,preco_total
count,31992.0,31992.000000,1.740500e+04,12171.000000,3.199200e+04,3.199200e+04,3.199200e+04
mean,2023.0,325851.174637,1.192257e+12,77.208096,3.181966e+05,3.164855e+02,1.537907e+05
std,0.0,76106.427867,2.142947e+11,198.456748,2.490772e+07,2.893993e+04,7.713037e+06
min,2023.0,209756.000000,1.002900e+12,0.200000,1.000000e+00,5.000000e-04,1.600000e-01
25%,2023.0,268273.000000,1.029805e+12,3.000000,3.000000e+02,4.000000e-01,8.274250e+02
50%,2023.0,273466.000000,1.097403e+12,15.000000,2.000000e+03,2.240000e+00,3.361470e+03
75%,2023.0,398689.000000,1.256802e+12,100.000000,1.200000e+04,8.080000e+00,1.761050e+04
max,2023.0,632036.000000,1.986000e+12,5000.000000,4.356140e+09,4.804290e+06,1.364418e+09

📌 ESTATÍSTICAS DESCRITIVAS (categóricas):

,nome_instituicao,esfera,cnpj_instituicao,municipio_instituicao,uf,compra,insercao,descricao_catmat,unidade_fornecimento,generico,modalidade_compra,tipo_compra,unidade_medida,unidade_fornecimento_capacidade,cnpj_fornecedor,fornecedor,cnpj_fabricante,fabricante
count,31979,31992,31992,31992,31992,31992,31276,31992,31992,17405,31992,31992,12171,31992,31992,31992,31992,31992
unique,214,2,272,254,19,255,501,5108,40,2,7,2,9,256,1102,1032,936,850
top,FUNDO MUNICIPAL DE SAUDE,MUNICIPAL,12.075.748/0001-32,FLORIANOPOLIS,PR,01/03/2023,27/04/2023,"CLORETO DE SÓDIO, PRINCÍPIO ATIVO:0,9%_ SOLUÇÃ...",COMPRIMIDO,S,Pregão,ADMINISTRATIVA,ML,COMPRIMIDO,12.889.035/0001-02,INOVAMED HOSPITALAR LTDA,73.856.593/0001-66,CRISTALIA PRODUTOS QUIMICOS FARMACEUTICOS LTDA
freq,7158,29020,1401,1401,4931,1494,1402,151,11349,10841,29078,31466,9907,11349,932,935,1896,2149

------------------------------------------------------------
============================================================
🔹 ANÁLISE EXPLORATÓRIA: Base 2024 (original)
============================================================

📌 SHAPE: 26258 linhas x 25 colunas

📌 COLUNAS E TIPOS:
ano_compra                           int64
nome_instituicao                       str
esfera                                 str
cnpj_instituicao                       str
municipio_instituicao                  str
uf                                     str
compra                                 str
insercao                               str
codigo_br                            int64
descricao_catmat                       str
unidade_fornecimento                   str
generico                               str
anvisa                             float64
modalidade_compra                      str
tipo_compra                            str
capacidade                         float64
unidade_medida                         str
unidade_fornecimento_capacidade        str
cnpj_fornecedor                        str
fornecedor                             str
cnpj_fabricante                        str
fabricante                             str
qtd_itens_comprados                  int64
preco_unitario                     float64
preco_total                        float64

📌 HEAD (primeiras 5 linhas):

,ano_compra,nome_instituicao,esfera,cnpj_instituicao,municipio_instituicao,uf,compra,insercao,codigo_br,descricao_catmat,...,capacidade,unidade_medida,unidade_fornecimento_capacidade,cnpj_fornecedor,fornecedor,cnpj_fabricante,fabricante,qtd_itens_comprados,preco_unitario,preco_total
0,2024,FUNDO MUNICIPAL DE SAUDE,MUNICIPAL,11.120.699/0001-40,MURICI,AL,01/01/2024,09/08/2024,268375,"ACICLOVIR, DOSAGEM:50 MG/G, USO:CREME",...,10.0,G,BISNAGA 10.00 G,00.236.193/0001-84,CIRURGICA RECIFE COMERCIO E REPRESENTACOES LTDA,73.856.593/0001-66,"PRATI, DONADUZZI & CIA LTDA",900,5.24,4716.0
1,2024,FUNDO MUNICIPAL DE SAUDE,MUNICIPAL,21.817.418/0001-66,URUPA,RO,01/01/2024,21/08/2025,267203,"DIPIRONA SÓDICA, DOSAGEM:500 MG",...,NaN,NaN,COMPRIMIDO,26.419.311/0001-83,LUMANN DISTRIBUIDORA DE MEDICAMENTOS LTDA,57.507.378/0001-01,EMS S/A,25000,0.17,4250.0
2,2024,FUNDO MUNICIPAL DE SAUDE,MUNICIPAL,11.120.699/0001-40,MURICI,AL,01/01/2024,09/08/2024,268370,"ACICLOVIR, DOSAGEM:200 MG",...,NaN,NaN,COMPRIMIDO,00.236.193/0001-84,CIRURGICA RECIFE COMERCIO E REPRESENTACOES LTDA,73.856.593/0001-66,"PRATI, DONADUZZI & CIA LTDA",600,0.33,198.0
3,2024,FUNDO MUNICIPAL DE SAUDE,MUNICIPAL,21.817.418/0001-66,URUPA,RO,01/01/2024,21/08/2025,383750,"LACTULOSE, CONCENTRAÇÃO:667 MG/ML, FORMA FARMA...",...,120.0,ML,FRASCO 120.00 ML,26.419.311/0001-83,LUMANN DISTRIBUIDORA DE MEDICAMENTOS LTDA,31.170.914/0001-24,MAYBEN PHARMACEUTICAL LTDA,50,4.99,249.5
4,2024,FUNDO MUNICIPAL DE SAUDE,MUNICIPAL,11.120.699/0001-40,MURICI,AL,01/01/2024,09/08/2024,320353,"ÁGUA DESTILADA, ASPECTO FÍSICO:LIVRE DE DNASE ...",...,NaN,NaN,MILILITRO,00.236.193/0001-84,CIRURGICA RECIFE COMERCIO E REPRESENTACOES LTDA,03.485.572/0001-04,GEOLAB INDUSTRIA FARMACEUTICA S/A,21000,0.45,9450.0

📌 TAIL (últimas 5 linhas):

,ano_compra,nome_instituicao,esfera,cnpj_instituicao,municipio_instituicao,uf,compra,insercao,codigo_br,descricao_catmat,...,capacidade,unidade_medida,unidade_fornecimento_capacidade,cnpj_fornecedor,fornecedor,cnpj_fabricante,fabricante,qtd_itens_comprados,preco_unitario,preco_total
26253,2024,SECRETARIA DE ESTADO DA SAUDE,ESTADUAL,46.374.500/0262-31,SAO PAULO,SP,30/12/2024,26/03/2025,448174,"EXTRATO MEDICINAL, PRINCÍPIO ATIVO:ESPINHEIRA ...",...,NaN,NaN,CÁPSULA,35.253.171/0001-07,AMP COMERCIO DE PRODUTOS HOSPITALARES LTDA,56.646.953/0001-86,LABORATORIO VITALAB LTDA,19000,0.9500,18050.00
26254,2024,SECRETARIA DE ESTADO DA SAUDE,ESTADUAL,46.374.500/0262-31,SAO PAULO,SP,30/12/2024,26/03/2025,273589,"PROPILTIOURACIL, DOSAGEM:100 MG",...,NaN,NaN,COMPRIMIDO,12.889.035/0001-02,INOVAMED HOSPITALAR LTDA,49.475.833/0001-06,BIOLAB SANUS FARMACEUTICA LTDA,21600,0.7611,16439.76
26255,2024,SECRETARIA DE ESTADO DA SAUDE,ESTADUAL,46.374.500/0262-31,SAO PAULO,SP,30/12/2024,26/03/2025,270120,"CLONAZEPAM, DOSAGEM:2,5 MG/ML, APRESENTAÇÃO:SO...",...,20.0,ML,FRASCO 20.00 ML,08.778.201/0001-26,DROGAFONTE LTDA,19.570.720/0001-10,HIPOLABOR FARMACEUTICA LTDA,372000,0.0895,33294.00
26256,2024,SECRETARIA DE ESTADO DA SAUDE,ESTADUAL,46.374.500/0262-31,SAO PAULO,SP,30/12/2024,14/03/2025,270120,"CLONAZEPAM, DOSAGEM:2,5 MG/ML, APRESENTAÇÃO:SO...",...,20.0,ML,FRASCO 20.00 ML,15.361.503/0001-60,ALFA & OMEGA MEDICAL LTDA,03.485.572/0001-04,GEOLAB INDUSTRIA FARMACEUTICA S/A,36,6.9000,248.40
26257,2024,SECRETARIA DE ESTADO DA SAUDE,ESTADUAL,46.374.500/0262-31,SAO PAULO,SP,30/12/2024,14/03/2025,393831,"CICLOBENZAPRINA CLORIDRATO, COMPOSIÇÃO:ASSOCIA...",...,NaN,NaN,COMPRIMIDO,15.361.503/0001-60,ALFA & OMEGA MEDICAL LTDA,57.507.378/0003-65,EMS S/A,180,2.0000,360.00

📌 INFO (resumo):
<class 'pandas.DataFrame'>
RangeIndex: 26258 entries, 0 to 26257
Data columns (total 25 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   ano_compra                       26258 non-null  int64
 1   nome_instituicao                 26181 non-null  str
 2   esfera                           26258 non-null  str
 3   cnpj_instituicao                 26258 non-null  str
 4   municipio_instituicao            26258 non-null  str
 5   uf                               26258 non-null  str
 6   compra                           26258 non-null  str
 7   insercao                         24966 non-null  str
 8   codigo_br                        26258 non-null  int64
 9   descricao_catmat                 26258 non-null  str
 10  unidade_fornecimento             26255 non-null  str
 11  generico                         17584 non-null  str
 12  anvisa                           17584 non-null  float64
 13  modalidade_compra                26258 non-null  str
 14  tipo_compra                      26258 non-null  str
 15  capacidade                       9550 non-null   float64
 16  unidade_medida                   9550 non-null   str
 17  unidade_fornecimento_capacidade  26255 non-null  str
 18  cnpj_fornecedor                  26258 non-null  str
 19  fornecedor                       26258 non-null  str
 20  cnpj_fabricante                  26258 non-null  str
 21  fabricante                       26258 non-null  str
 22  qtd_itens_comprados              26258 non-null  int64
 23  preco_unitario                   26258 non-null  float64
 24  preco_total                      26258 non-null  float64
dtypes: float64(4), int64(3), str(18)
memory usage: 5.0 MB


📌 ESTATÍSTICAS DESCRITIVAS (numéricas):

,ano_compra,codigo_br,anvisa,capacidade,qtd_itens_comprados,preco_unitario,preco_total
count,26258.0,26258.000000,1.758400e+04,9550.000000,2.625800e+04,2.625800e+04,2.625800e+04
mean,2024.0,328799.507579,1.187788e+12,66.352394,2.028698e+05,7.489153e+02,3.414623e+05
std,0.0,80507.806695,2.169841e+11,167.344830,3.667092e+06,5.373051e+04,1.332020e+07
min,2024.0,209754.000000,1.002900e+12,0.200000,1.000000e+00,1.000000e-02,2.030000e-01
25%,2024.0,268286.000000,1.029803e+12,3.000000,3.600000e+02,3.290000e-01,9.028500e+02
50%,2024.0,273710.000000,1.091701e+12,15.000000,2.250000e+03,1.820000e+00,4.080000e+03
75%,2024.0,400852.000000,1.256802e+12,80.000000,1.778000e+04,7.267500e+00,2.016000e+04
max,2024.0,633819.000000,1.986000e+12,5000.000000,2.468743e+08,8.191720e+06,1.662919e+09

📌 ESTATÍSTICAS DESCRITIVAS (categóricas):

,nome_instituicao,esfera,cnpj_instituicao,municipio_instituicao,uf,compra,insercao,descricao_catmat,unidade_fornecimento,generico,modalidade_compra,tipo_compra,unidade_medida,unidade_fornecimento_capacidade,cnpj_fornecedor,fornecedor,cnpj_fabricante,fabricante
count,26181,26258,26258,26258,26258,26258,24966,26258,26255,17584,26258,26258,9550,26255,26258,26258,26258,26258
unique,177,2,230,221,19,309,383,4219,39,2,7,2,11,256,1068,983,757,701
top,FUNDO MUNICIPAL DE SAUDE,MUNICIPAL,46.374.500/0262-31,SAO PAULO,SP,05/06/2024,26/03/2025,"CLORETO DE SÓDIO, PRINCÍPIO ATIVO:0,9%_ SOLUÇÃ...",COMPRIMIDO,N,Pregão,ADMINISTRATIVA,ML,COMPRIMIDO,44.734.671/0022-86,CRISTALIA PRODUTOS QUIMICOS FARMACEUTICOS LTDA,73.856.593/0001-66,EMS S/A
freq,4966,23501,1247,1247,5243,711,632,150,10779,8922,21609,23997,7716,10779,785,886,1836,2307

------------------------------------------------------------
============================================================
🔹 ANÁLISE EXPLORATÓRIA: Base 2025 (original)
============================================================

📌 SHAPE: 26215 linhas x 25 colunas

📌 COLUNAS E TIPOS:
ano_compra                           int64
nome_instituicao                       str
esfera                                 str
cnpj_instituicao                       str
municipio_instituicao                  str
uf                                     str
compra                                 str
insercao                               str
codigo_br                            int64
descricao_catmat                       str
unidade_fornecimento                   str
generico                               str
anvisa                             float64
modalidade_compra                      str
tipo_compra                            str
capacidade                         float64
unidade_medida                         str
unidade_fornecimento_capacidade        str
cnpj_fornecedor                        str
fornecedor                             str
cnpj_fabricante                        str
fabricante                             str
qtd_itens_comprados                  int64
preco_unitario                     float64
preco_total                        float64

📌 HEAD (primeiras 5 linhas):

,ano_compra,nome_instituicao,esfera,cnpj_instituicao,municipio_instituicao,uf,compra,insercao,codigo_br,descricao_catmat,...,capacidade,unidade_medida,unidade_fornecimento_capacidade,cnpj_fornecedor,fornecedor,cnpj_fabricante,fabricante,qtd_itens_comprados,preco_unitario,preco_total
0,2025,FUNDO MUNICIPAL DE SAUDE,MUNICIPAL,11.328.684/0001-71,SAO FRANCISCO DO GUAPORE,RO,01/01/2025,01/09/2025,342134,"HIDROCORTISONA, COMPOSIÇÃO:SAL SUCCINATO SÓDIC...",...,NaN,NaN,FRASCO-AMPOLA,58.430.828/0001-60,BLAU FARMACEUTICA S.A.,58.430.828/0001-60,BLAU FARMACEUTICA S.A.,200,11.91,2382.00
1,2025,FUNDO MUNICIPAL DE SAUDE,MUNICIPAL,11.328.684/0001-71,SAO FRANCISCO DO GUAPORE,RO,01/01/2025,01/09/2025,267772,"PROPRANOLOL CLORIDRATO, DOSAGEM:40 MG",...,NaN,NaN,COMPRIMIDO,19.791.813/0001-75,LABORATORIOS OSORIO DE MORAES LTDA,19.791.813/0001-75,LABORATORIOS OSORIO DE MORAES LTDA,5000,0.05,250.00
2,2025,FUNDO MUNICIPAL DE SAUDE,MUNICIPAL,11.328.684/0001-71,SAO FRANCISCO DO GUAPORE,RO,01/01/2025,01/09/2025,267310,"METOCLOPRAMIDA CLORIDRATO, DOSAGEM:5 MG/ML, AP...",...,2.0,ML,AMPOLA 2.00 ML,01.571.702/0001-98,HALEX ISTAR INDUSTRIA FARMACEUTICA SA,01.571.702/0001-98,HALEX ISTAR INDUSTRIA FARMACEUTICA SA,300,0.81,243.00
3,2025,FUNDO MUNICIPAL DE SAUDE,MUNICIPAL,21.817.418/0001-66,URUPA,RO,01/01/2025,21/08/2025,272796,"HEPARINA SÓDICA, DOSAGEM:5.000UI/ML, INDICAÇÃO...",...,5.0,ML,FRASCO 5.00 ML,23.662.749/0001-08,M GREFFE DE OLIVEIRA LIMA,58.430.828/0005-93,BLAU FARMACEUTICA S.A.,25,25.71,642.75
4,2025,FUNDO MUNICIPAL DE SAUDE,MUNICIPAL,11.328.684/0001-71,SAO FRANCISCO DO GUAPORE,RO,01/01/2025,01/09/2025,270612,"BENZILPENICILINA, APRESENTAÇÃO:BENZATINA, DOSA...",...,NaN,NaN,FRASCO-AMPOLA,17.159.229/0001-76,LABORATORIO TEUTO BRASILEIRO S/A,17.159.229/0001-76,LABORATORIO TEUTO BRASILEIRO S/A,200,8.35,1670.00

📌 TAIL (últimas 5 linhas):

,ano_compra,nome_instituicao,esfera,cnpj_instituicao,municipio_instituicao,uf,compra,insercao,codigo_br,descricao_catmat,...,capacidade,unidade_medida,unidade_fornecimento_capacidade,cnpj_fornecedor,fornecedor,cnpj_fabricante,fabricante,qtd_itens_comprados,preco_unitario,preco_total
26210,2025,MUNICIPIO DE DOURADOQUARA,MUNICIPAL,18.158.261/0001-08,DOURADOQUARA,MG,29/12/2025,04/03/2026,267505,"ÁCIDO VALPRÓICO, DOSAGEM:500 MG",...,NaN,NaN,COMPRIMIDO,42.799.163/0001-26,BH FARMA COMERCIO LTDA,56.998.701/0001-16,ABBOTT LABORATORIOS DO BRASIL LTDA,2500,0.5800,1450.0
26211,2025,MUNICIPIO DE DOURADOQUARA,MUNICIPAL,18.158.261/0001-08,DOURADOQUARA,MG,29/12/2025,04/03/2026,268960,"DOPAMINA, DOSAGEM:5 MG/ML, APRESENTAÇÃO:SOLUÇÃ...",...,10.0,ML,AMPOLA 10.00 ML,18.917.657/0001-83,MEDH DISTRIBUIDORA DE MEDICAMENTOS LTDA,17.159.229/0001-76,LABORATORIO TEUTO BRASILEIRO S/A,50,3.0000,150.0
26212,2025,MUNICIPIO DE DOURADOQUARA,MUNICIPAL,18.158.261/0001-08,DOURADOQUARA,MG,29/12/2025,04/03/2026,291771,"ESCITALOPRAM OXALATO, DOSAGEM:20 MG",...,NaN,NaN,COMPRIMIDO,18.917.657/0001-83,MEDH DISTRIBUIDORA DE MEDICAMENTOS LTDA,57.507.378/0003-65,EMS S/A,1000,0.1700,170.0
26213,2025,MUNICIPIO DE DOURADOQUARA,MUNICIPAL,18.158.261/0001-08,DOURADOQUARA,MG,30/12/2025,04/03/2026,267676,"IBUPROFENO, DOSAGEM:600 MG",...,NaN,NaN,COMPRIMIDO,73.856.593/0010-57,"PRATI, DONADUZZI & CIA LTDA",73.856.593/0001-66,"PRATI, DONADUZZI & CIA LTDA",2500,0.1192,298.0
26214,2025,MUNICIPIO DE DOURADOQUARA,MUNICIPAL,18.158.261/0001-08,DOURADOQUARA,MG,30/12/2025,03/03/2026,271950,"FENTANILA, APRESENTAÇÃO:SAL CITRATO, DOSAGEM:0...",...,2.0,ML,AMPOLA 2.00 ML,26.457.348/0001-04,C.A. HOSPITALAR LTDA,19.570.720/0001-10,HIPOLABOR FARMACEUTICA LTDA,50,2.4000,120.0

📌 INFO (resumo):
<class 'pandas.DataFrame'>
RangeIndex: 26215 entries, 0 to 26214
Data columns (total 25 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   ano_compra                       26215 non-null  int64
 1   nome_instituicao                 26156 non-null  str
 2   esfera                           26215 non-null  str
 3   cnpj_instituicao                 26215 non-null  str
 4   municipio_instituicao            26215 non-null  str
 5   uf                               26215 non-null  str
 6   compra                           26215 non-null  str
 7   insercao                         26215 non-null  str
 8   codigo_br                        26215 non-null  int64
 9   descricao_catmat                 26215 non-null  str
 10  unidade_fornecimento             26207 non-null  str
 11  generico                         19503 non-null  str
 12  anvisa                           19503 non-null  float64
 13  modalidade_compra                26215 non-null  str
 14  tipo_compra                      26215 non-null  str
 15  capacidade                       9676 non-null   float64
 16  unidade_medida                   9676 non-null   str
 17  unidade_fornecimento_capacidade  26207 non-null  str
 18  cnpj_fornecedor                  26215 non-null  str
 19  fornecedor                       26215 non-null  str
 20  cnpj_fabricante                  26215 non-null  str
 21  fabricante                       26215 non-null  str
 22  qtd_itens_comprados              26215 non-null  int64
 23  preco_unitario                   26215 non-null  float64
 24  preco_total                      26215 non-null  float64
dtypes: float64(4), int64(3), str(18)
memory usage: 5.0 MB


📌 ESTATÍSTICAS DESCRITIVAS (numéricas):

,ano_compra,codigo_br,anvisa,capacidade,qtd_itens_comprados,preco_unitario,preco_total
count,26215.0,26215.000000,1.950300e+04,9676.000000,2.621500e+04,26215.000000,2.621500e+04
mean,2025.0,335725.273584,1.175154e+12,68.276287,2.555141e+05,294.140377,1.332477e+06
std,0.0,85542.505197,2.154894e+11,182.214349,3.076919e+06,6240.763070,1.428167e+08
min,2025.0,233632.000000,1.002900e+12,0.050000,1.000000e+00,0.003000,1.560000e-01
25%,2025.0,268471.000000,1.029800e+12,3.000000,3.000000e+02,0.370000,9.442500e+02
50%,2025.0,278281.000000,1.057302e+12,10.000000,2.000000e+03,2.100000,4.224000e+03
75%,2025.0,411438.000000,1.256801e+12,100.000000,1.787000e+04,8.255000,2.411350e+04
max,2025.0,635152.000000,1.986000e+12,5000.000000,1.351164e+08,639303.910000,2.281600e+10

📌 ESTATÍSTICAS DESCRITIVAS (categóricas):

,nome_instituicao,esfera,cnpj_instituicao,municipio_instituicao,uf,compra,insercao,descricao_catmat,unidade_fornecimento,generico,modalidade_compra,tipo_compra,unidade_medida,unidade_fornecimento_capacidade,cnpj_fornecedor,fornecedor,cnpj_fabricante,fabricante
count,26156,26215,26215,26215,26215,26215,26215,26215,26207,19503,26215,26215,9676,26207,26215,26215,26215,26215
unique,138,2,174,167,20,328,246,4469,38,2,5,2,11,250,1083,983,751,696
top,FUNDO MUNICIPAL DE SAUDE,MUNICIPAL,46.374.500/0262-31,SAO PAULO,RO,20/06/2025,29/12/2025,"CLORETO DE SÓDIO, PRINCÍPIO ATIVO:0,9%_ SOLUÇÃ...",COMPRIMIDO,N,Pregão,ADMINISTRATIVA,ML,COMPRIMIDO,31.187.918/0001-15,ALLFAMED COMERCIO ATACADISTA DE MEDICAMENTOS LTDA,57.507.378/0003-65,EMS S/A
freq,4928,21804,1466,1466,3783,875,790,144,9760,10217,20878,23923,7838,9760,1006,1006,1685,2048

------------------------------------------------------------
============================================================
🔹 ANÁLISE EXPLORATÓRIA: Base 2026 (original)
============================================================

📌 SHAPE: 819 linhas x 25 colunas

📌 COLUNAS E TIPOS:
ano_compra                           int64
nome_instituicao                       str
esfera                                 str
cnpj_instituicao                       str
municipio_instituicao                  str
uf                                     str
compra                                 str
insercao                               str
codigo_br                            int64
descricao_catmat                       str
unidade_fornecimento                   str
generico                               str
anvisa                             float64
modalidade_compra                      str
tipo_compra                            str
capacidade                         float64
unidade_medida                         str
unidade_fornecimento_capacidade        str
cnpj_fornecedor                        str
fornecedor                             str
cnpj_fabricante                        str
fabricante                             str
qtd_itens_comprados                  int64
preco_unitario                     float64
preco_total                        float64

📌 HEAD (primeiras 5 linhas):

,ano_compra,nome_instituicao,esfera,cnpj_instituicao,municipio_instituicao,uf,compra,insercao,codigo_br,descricao_catmat,...,capacidade,unidade_medida,unidade_fornecimento_capacidade,cnpj_fornecedor,fornecedor,cnpj_fabricante,fabricante,qtd_itens_comprados,preco_unitario,preco_total
0,2026,MUNICIPIO DE PATOS DE MINAS,MUNICIPAL,18.602.011/0001-07,PATOS DE MINAS,MG,06/01/2026,27/01/2026,484594,"TUBO ENDOBRONQUIAL, MODELO:DUPLO LÚMEN C/ GANC...",...,NaN,NaN,UNIDADE,17.159.229/0002-57,LABORATORIO TEUTO BRASILEIRO S/A,17.159.229/0001-76,LABORATORIO TEUTO BRASILEIRO S/A,1000,0.99,990.0
1,2026,MUNICIPIO DE DOURADOQUARA,MUNICIPAL,18.158.261/0001-08,DOURADOQUARA,MG,06/01/2026,03/03/2026,405899,"DESVENLAFAXINA, COMPOSIÇÃO:SAL SUCCINATO, CONC...",...,NaN,NaN,COMPRIMIDO,12.927.876/0001-67,SOMA/MG PRODUTOS HOSPITALARES LTDA,57.507.378/0003-65,EMS S/A,800,0.74,592.0
2,2026,MUNICIPIO DE PATOS DE MINAS,MUNICIPAL,18.602.011/0001-07,PATOS DE MINAS,MG,06/01/2026,27/01/2026,439252,"NUSINERSENA, CONCENTRAÇÃO:2,4 MG/ML, FORMA FAR...",...,5.0,ML,FRASCO 5.00 ML,17.159.229/0002-57,LABORATORIO TEUTO BRASILEIRO S/A,07.986.222/0001-74,BIOGEN BRASIL PRODUTOS FARMACEUTICOS LTDA,10,415789.90,4157899.0
3,2026,MUNICIPIO DE DOURADOQUARA,MUNICIPAL,18.158.261/0001-08,DOURADOQUARA,MG,06/01/2026,03/03/2026,282881,"ROSUVASTATINA, COMPOSIÇÃO:CÁLCICA, CONCENTRAÇÃ...",...,NaN,NaN,COMPRIMIDO,12.927.876/0001-67,SOMA/MG PRODUTOS HOSPITALARES LTDA,02.814.497/0001-07,CIMED INDUSTRIA S.A.,800,0.13,104.0
4,2026,MUNICIPIO DE DOURADOQUARA,MUNICIPAL,18.158.261/0001-08,DOURADOQUARA,MG,06/01/2026,03/03/2026,302442,"DULOXETINA, CONCENTRAÇÃO:30 MG, FORMA FARMACÊU...",...,NaN,NaN,CÁPSULA,12.927.876/0001-67,SOMA/MG PRODUTOS HOSPITALARES LTDA,57.507.378/0003-65,EMS S/A,1500,0.68,1020.0

📌 TAIL (últimas 5 linhas):

,ano_compra,nome_instituicao,esfera,cnpj_instituicao,municipio_instituicao,uf,compra,insercao,codigo_br,descricao_catmat,...,capacidade,unidade_medida,unidade_fornecimento_capacidade,cnpj_fornecedor,fornecedor,cnpj_fabricante,fabricante,qtd_itens_comprados,preco_unitario,preco_total
814,2026,FUNDO ESTADUAL DE SAUDE DO ESTADO DA BAHIA,ESTADUAL,05.816.630/0001-52,SALVADOR,BA,04/03/2026,11/03/2026,272023,"TAMOXIFENO CITRATO, DOSAGEM:20 MG",...,NaN,NaN,COMPRIMIDO,96.827.563/0001-27,MEDISIL MEDICAMENTOS LTDA,57.507.378/0003-65,EMS S/A,209000,0.42,87780.0
815,2026,FUNDO ESTADUAL DE SAUDE DO ESTADO DA BAHIA,ESTADUAL,05.816.630/0001-52,SALVADOR,BA,04/03/2026,11/03/2026,448772,"VANCOMICINA CLORIDRATO, CONCENTRAÇÃO:500 MG, F...",...,NaN,NaN,FRASCO-AMPOLA,96.827.563/0001-27,MEDISIL MEDICAMENTOS LTDA,49.324.221/0001-04,FRESENIUS KABI BRASIL LTDA.,296400,4.71,1396044.0
816,2026,FUNDO ESTADUAL DE SAUDE DO ESTADO DA BAHIA,ESTADUAL,05.816.630/0001-52,SALVADOR,BA,05/03/2026,11/03/2026,273474,"MILRINONA, DOSAGEM:1 MG/ML, TIPO MEDICAMENTO:S...",...,10.0,ML,FRASCO 10.00 ML,96.827.563/0001-27,MEDISIL MEDICAMENTOS LTDA,09.058.502/0001-48,FARMA VISION IMPORTACAO E EXPORTACAO DE MEDICA...,3040,57.22,173948.8
817,2026,FUNDO ESTADUAL DE SAUDE DO ESTADO DA BAHIA,ESTADUAL,05.816.630/0001-52,SALVADOR,BA,05/03/2026,11/03/2026,280116,"BOSENTANA, DOSAGEM:62,5 MG",...,NaN,NaN,COMPRIMIDO,15.145.035/0001-96,RIOBAHIAFARMA COMERCIO E DISTRIBUICAO DE PRODU...,73.663.650/0001-90,RANBAXY FARMACEUTICA LTDA,3420,16.69,57079.8
818,2026,FUNDO ESTADUAL DE SAUDE DO ESTADO DA BAHIA,ESTADUAL,05.816.630/0001-52,SALVADOR,BA,05/03/2026,11/03/2026,352204,"DEXMEDETOMIDINA CLORIDRATO, CONCENTRAÇAO:100 M...",...,2.0,ML,FRASCO 2.00 ML,60.665.981/0009-75,UNIAO QUIMICA FARMACEUTICA NACIONAL S A,60.665.981/0001-18,UNIAO QUIMICA FARMACEUTICA NACIONAL S A,103550,5.60,579880.0

📌 INFO (resumo):
<class 'pandas.DataFrame'>
RangeIndex: 819 entries, 0 to 818
Data columns (total 25 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   ano_compra                       819 non-null    int64
 1   nome_instituicao                 819 non-null    str
 2   esfera                           819 non-null    str
 3   cnpj_instituicao                 819 non-null    str
 4   municipio_instituicao            819 non-null    str
 5   uf                               819 non-null    str
 6   compra                           819 non-null    str
 7   insercao                         819 non-null    str
 8   codigo_br                        819 non-null    int64
 9   descricao_catmat                 819 non-null    str
 10  unidade_fornecimento             819 non-null    str
 11  generico                         651 non-null    str
 12  anvisa                           651 non-null    float64
 13  modalidade_compra                819 non-null    str
 14  tipo_compra                      819 non-null    str
 15  capacidade                       335 non-null    float64
 16  unidade_medida                   335 non-null    str
 17  unidade_fornecimento_capacidade  819 non-null    str
 18  cnpj_fornecedor                  819 non-null    str
 19  fornecedor                       819 non-null    str
 20  cnpj_fabricante                  819 non-null    str
 21  fabricante                       819 non-null    str
 22  qtd_itens_comprados              819 non-null    int64
 23  preco_unitario                   819 non-null    float64
 24  preco_total                      819 non-null    float64
dtypes: float64(4), int64(3), str(18)
memory usage: 160.1 KB


📌 ESTATÍSTICAS DESCRITIVAS (numéricas):

,ano_compra,codigo_br,anvisa,capacidade,qtd_itens_comprados,preco_unitario,preco_total
count,819.0,819.000000,6.510000e+02,335.000000,8.190000e+02,819.000000,8.190000e+02
mean,2026.0,335135.343101,1.165876e+12,73.890149,3.445717e+05,748.318595,5.120488e+05
std,0.0,85219.389840,2.012549e+11,135.685517,8.313118e+06,14710.525900,4.981603e+06
min,2026.0,242918.000000,1.003302e+12,0.200000,2.000000e+00,0.030000,8.800000e+00
25%,2026.0,268520.500000,1.029800e+12,5.000000,2.160000e+02,0.460000,3.962000e+02
50%,2026.0,281657.000000,1.057101e+12,20.000000,1.500000e+03,2.840000,3.240000e+03
75%,2026.0,405898.000000,1.256800e+12,100.000000,9.450000e+03,8.685000,2.982960e+04
max,2026.0,623795.000000,1.935700e+12,1000.000000,2.378001e+08,415789.900000,1.260340e+08

📌 ESTATÍSTICAS DESCRITIVAS (categóricas):

,nome_instituicao,esfera,cnpj_instituicao,municipio_instituicao,uf,compra,insercao,descricao_catmat,unidade_fornecimento,generico,modalidade_compra,tipo_compra,unidade_medida,unidade_fornecimento_capacidade,cnpj_fornecedor,fornecedor,cnpj_fabricante,fabricante
count,819,819,819,819,819,819,819,819,819,651,819,819,335,819,819,819,819,819
unique,15,2,17,16,11,30,26,591,22,2,3,2,5,70,137,126,144,139
top,FUNDO MUNICIPAL DE SAUDE,MUNICIPAL,11.429.173/0001-46,RIO BANANAL,SE,07/01/2026,11/02/2026,"CLORETO DE SÓDIO, PRINCÍPIO ATIVO:0,9%_ SOLUÇÃ...",COMPRIMIDO,N,Pregão,ADMINISTRATIVA,ML,COMPRIMIDO,16.647.278/0001-95,PARAMED DISTRIBUIDORA DE MEDICAMENTOS LTDA,57.507.378/0003-65,EMS S/A
freq,217,606,180,180,189,180,186,7,280,336,553,696,278,280,71,71,58,59

------------------------------------------------------------

In [20]:
# ============================================
# SPRINT 2: Verificar e padronizar os nomes das colunas
# ============================================

for ano, df in dataframes.items():
    print(f"{ano}: {df.shape[1]} colunas")

# 3. Verificar se todos têm as mesmas colunas
colunas_referencia = dataframes[2020].columns
todos_iguais = all(df.columns.equals(colunas_referencia) for df in dataframes.values())

if todos_iguais:
    print("\n✅ Todos os arquivos têm exatamente as mesmas colunas e ordem!")
else:
    print("\n⚠️ Há diferenças nas colunas. Serão padronizadas.")

# 4. Padronizar nomes das colunas
def padronizar_nomes_colunas(df):
    cols = df.columns.tolist()
    novos_nomes = []
    for col in cols:
        col = col.lower()
        col = col.replace(' ', '_').replace('-', '_')
        col = unicodedata.normalize('NFKD', col).encode('ASCII', 'ignore').decode('ASCII')
        novos_nomes.append(col)
    df.columns = novos_nomes
    return df

for ano, df in dataframes.items():
    dataframes[ano] = padronizar_nomes_colunas(df)

# 5. Verificar novamente após padronização
colunas_referencia = dataframes[2020].columns
todos_iguais_apos = all(df.columns.equals(colunas_referencia) for df in dataframes.values())

if todos_iguais_apos:
    print("\n✅ Após padronização, todos os DataFrames têm as mesmas colunas!")
else:
    print("\n❌ Ainda há diferenças. Verifique manualmente.")

# 6. Exibir os nomes padronizados
print("\n📌 Nomes padronizados das colunas (exemplo 2020):")
print(dataframes[2020].columns.tolist())

2020: 25 colunas
2021: 25 colunas
2022: 25 colunas
2023: 25 colunas
2024: 25 colunas
2025: 25 colunas
2026: 25 colunas

✅ Todos os arquivos têm exatamente as mesmas colunas e ordem!

✅ Após padronização, todos os DataFrames têm as mesmas colunas!

📌 Nomes padronizados das colunas (exemplo 2020):
['ano_compra', 'nome_instituicao', 'esfera', 'cnpj_instituicao', 'municipio_instituicao', 'uf', 'compra', 'insercao', 'codigo_br', 'descricao_catmat', 'unidade_fornecimento', 'generico', 'anvisa', 'modalidade_compra', 'tipo_compra', 'capacidade', 'unidade_medida', 'unidade_fornecimento_capacidade', 'cnpj_fornecedor', 'fornecedor', 'cnpj_fabricante', 'fabricante', 'qtd_itens_comprados', 'preco_unitario', 'preco_total']

In [21]:
# ============================================
# SPRINT 2: Verificar tipos de dados (por arquivo)
# ============================================

print("="*60)
print("DIAGNÓSTICO DE TIPOS DE DADOS (ANO A ANO)")
print("="*60)

# Lista dos DataFrames carregados
anos = [2020, 2021, 2022, 2023, 2024, 2025, 2026]

# 1. Verificar tipos de cada coluna por ano
print("\n📌 TIPOS DE DADOS POR ANO:\n")
for ano in anos:
    df = dataframes[ano]  # usa o dicionário criado anteriormente
    print(f"--- {ano} ---")
    print(df.dtypes)
    print("-" * 40)

# 2. Identificar colunas com tipos inconsistentes entre os anos
print("\n📌 VERIFICANDO CONSISTÊNCIA DE TIPOS ENTRE OS ANOS:\n")

# Pegar todas as colunas (assumindo que são iguais)
colunas = dataframes[2020].columns

for col in colunas:
    tipos = {}
    for ano in anos:
        df = dataframes[ano]
        if col in df.columns:
            tipo = df[col].dtype
            tipos[ano] = str(tipo)
    # Verificar se todos os tipos são iguais
    if len(set(tipos.values())) > 1:
        print(f"⚠️ Coluna '{col}' tem tipos diferentes entre os anos:")
        for ano, tipo in tipos.items():
            print(f"   {ano}: {tipo}")
    else:
        print(f"✅ Coluna '{col}': consistente ({list(tipos.values())[0]})")

# 3. Verificar colunas que podem ter problemas de formato (ex: vírgula como decimal)
print("\n📌 VERIFICANDO POSSÍVEIS PROBLEMAS DE FORMATO:\n")

colunas_numericas = ['preco_unitario', 'preco_total', 'capacidade']
for col in colunas_numericas:
    if col in dataframes[2020].columns:
        print(f"\n🔍 Coluna: {col}")
        for ano in anos:
            df = dataframes[ano]
            # Verificar se a coluna é object (possível problema de vírgula)
            if df[col].dtype == 'object':
                # Amostra de valores
                amostra = df[col].dropna().head(5)
                if not amostra.empty:
                    print(f"   {ano}: object (amostra: {amostra.tolist()})")
            else:
                print(f"   {ano}: {df[col].dtype}")

# 4. Verificar colunas de data
print("\n📌 VERIFICANDO COLUNAS DE DATA:\n")
colunas_data = ['compra', 'insercao']
for col in colunas_data:
    if col in dataframes[2020].columns:
        print(f"\n🔍 Coluna: {col}")
        for ano in anos:
            df = dataframes[ano]
            if df[col].dtype == 'object':
                # Amostra de valores
                amostra = df[col].dropna().head(3)
                if not amostra.empty:
                    print(f"   {ano}: object (exemplo: {amostra.iloc[0]})")
            else:
                print(f"   {ano}: {df[col].dtype}")

print("\n✅ Diagnóstico concluído!")

============================================================
DIAGNÓSTICO DE TIPOS DE DADOS (ANO A ANO)
============================================================

📌 TIPOS DE DADOS POR ANO:

--- 2020 ---
ano_compra                           int64
nome_instituicao                       str
esfera                                 str
cnpj_instituicao                       str
municipio_instituicao                  str
uf                                     str
compra                                 str
insercao                               str
codigo_br                            int64
descricao_catmat                       str
unidade_fornecimento                   str
generico                               str
anvisa                             float64
modalidade_compra                      str
tipo_compra                            str
capacidade                         float64
unidade_medida                         str
unidade_fornecimento_capacidade        str
cnpj_fornecedor                        str
fornecedor                             str
cnpj_fabricante                        str
fabricante                             str
qtd_itens_comprados                  int64
preco_unitario                     float64
preco_total                        float64
dtype: object
----------------------------------------
--- 2021 ---
ano_compra                           int64
nome_instituicao                       str
esfera                                 str
cnpj_instituicao                       str
municipio_instituicao                  str
uf                                     str
compra                                 str
insercao                               str
codigo_br                            int64
descricao_catmat                       str
unidade_fornecimento                   str
generico                               str
anvisa                             float64
modalidade_compra                      str
tipo_compra                            str
capacidade                         float64
unidade_medida                         str
unidade_fornecimento_capacidade        str
cnpj_fornecedor                        str
fornecedor                             str
cnpj_fabricante                        str
fabricante                             str
qtd_itens_comprados                  int64
preco_unitario                     float64
preco_total                        float64
dtype: object
----------------------------------------
--- 2022 ---
ano_compra                           int64
nome_instituicao                       str
esfera                                 str
cnpj_instituicao                       str
municipio_instituicao                  str
uf                                     str
compra                                 str
insercao                               str
codigo_br                            int64
descricao_catmat                       str
unidade_fornecimento                   str
generico                               str
anvisa                             float64
modalidade_compra                      str
tipo_compra                            str
capacidade                         float64
unidade_medida                         str
unidade_fornecimento_capacidade        str
cnpj_fornecedor                        str
fornecedor                             str
cnpj_fabricante                        str
fabricante                             str
qtd_itens_comprados                  int64
preco_unitario                     float64
preco_total                        float64
dtype: object
----------------------------------------
--- 2023 ---
ano_compra                           int64
nome_instituicao                       str
esfera                                 str
cnpj_instituicao                       str
municipio_instituicao                  str
uf                                     str
compra                                 str
insercao                               str
codigo_br                            int64
descricao_catmat                       str
unidade_fornecimento                   str
generico                               str
anvisa                             float64
modalidade_compra                      str
tipo_compra                            str
capacidade                         float64
unidade_medida                         str
unidade_fornecimento_capacidade        str
cnpj_fornecedor                        str
fornecedor                             str
cnpj_fabricante                        str
fabricante                             str
qtd_itens_comprados                  int64
preco_unitario                     float64
preco_total                        float64
dtype: object
----------------------------------------
--- 2024 ---
ano_compra                           int64
nome_instituicao                       str
esfera                                 str
cnpj_instituicao                       str
municipio_instituicao                  str
uf                                     str
compra                                 str
insercao                               str
codigo_br                            int64
descricao_catmat                       str
unidade_fornecimento                   str
generico                               str
anvisa                             float64
modalidade_compra                      str
tipo_compra                            str
capacidade                         float64
unidade_medida                         str
unidade_fornecimento_capacidade        str
cnpj_fornecedor                        str
fornecedor                             str
cnpj_fabricante                        str
fabricante                             str
qtd_itens_comprados                  int64
preco_unitario                     float64
preco_total                        float64
dtype: object
----------------------------------------
--- 2025 ---
ano_compra                           int64
nome_instituicao                       str
esfera                                 str
cnpj_instituicao                       str
municipio_instituicao                  str
uf                                     str
compra                                 str
insercao                               str
codigo_br                            int64
descricao_catmat                       str
unidade_fornecimento                   str
generico                               str
anvisa                             float64
modalidade_compra                      str
tipo_compra                            str
capacidade                         float64
unidade_medida                         str
unidade_fornecimento_capacidade        str
cnpj_fornecedor                        str
fornecedor                             str
cnpj_fabricante                        str
fabricante                             str
qtd_itens_comprados                  int64
preco_unitario                     float64
preco_total                        float64
dtype: object
----------------------------------------
--- 2026 ---
ano_compra                           int64
nome_instituicao                       str
esfera                                 str
cnpj_instituicao                       str
municipio_instituicao                  str
uf                                     str
compra                                 str
insercao                               str
codigo_br                            int64
descricao_catmat                       str
unidade_fornecimento                   str
generico                               str
anvisa                             float64
modalidade_compra                      str
tipo_compra                            str
capacidade                         float64
unidade_medida                         str
unidade_fornecimento_capacidade        str
cnpj_fornecedor                        str
fornecedor                             str
cnpj_fabricante                        str
fabricante                             str
qtd_itens_comprados                  int64
preco_unitario                     float64
preco_total                        float64
dtype: object
----------------------------------------

📌 VERIFICANDO CONSISTÊNCIA DE TIPOS ENTRE OS ANOS:

✅ Coluna 'ano_compra': consistente (int64)
✅ Coluna 'nome_instituicao': consistente (str)
✅ Coluna 'esfera': consistente (str)
✅ Coluna 'cnpj_instituicao': consistente (str)
✅ Coluna 'municipio_instituicao': consistente (str)
✅ Coluna 'uf': consistente (str)
✅ Coluna 'compra': consistente (str)
✅ Coluna 'insercao': consistente (str)
✅ Coluna 'codigo_br': consistente (int64)
✅ Coluna 'descricao_catmat': consistente (str)
✅ Coluna 'unidade_fornecimento': consistente (str)
✅ Coluna 'generico': consistente (str)
✅ Coluna 'anvisa': consistente (float64)
✅ Coluna 'modalidade_compra': consistente (str)
✅ Coluna 'tipo_compra': consistente (str)
✅ Coluna 'capacidade': consistente (float64)
✅ Coluna 'unidade_medida': consistente (str)
✅ Coluna 'unidade_fornecimento_capacidade': consistente (str)
✅ Coluna 'cnpj_fornecedor': consistente (str)
✅ Coluna 'fornecedor': consistente (str)
✅ Coluna 'cnpj_fabricante': consistente (str)
✅ Coluna 'fabricante': consistente (str)
✅ Coluna 'qtd_itens_comprados': consistente (int64)
✅ Coluna 'preco_unitario': consistente (float64)
✅ Coluna 'preco_total': consistente (float64)

📌 VERIFICANDO POSSÍVEIS PROBLEMAS DE FORMATO:


🔍 Coluna: preco_unitario
   2020: float64
   2021: float64
   2022: float64
   2023: float64
   2024: float64
   2025: float64
   2026: float64

🔍 Coluna: preco_total
   2020: float64
   2021: float64
   2022: float64
   2023: float64
   2024: float64
   2025: float64
   2026: float64

🔍 Coluna: capacidade
   2020: float64
   2021: float64
   2022: float64
   2023: float64
   2024: float64
   2025: float64
   2026: float64

📌 VERIFICANDO COLUNAS DE DATA:


🔍 Coluna: compra
   2020: str
   2021: str
   2022: str
   2023: str
   2024: str
   2025: str
   2026: str

🔍 Coluna: insercao
   2020: str
   2021: str
   2022: str
   2023: str
   2024: str
   2025: str
   2026: str

✅ Diagnóstico concluído!

In [22]:
# ============================================
# SPRINT 2: Corrigir tipos de dados
# ============================================

print("🔹 Corrigindo tipos de dados...")

# Lista de anos
anos = [2020, 2021, 2022, 2023, 2024, 2025, 2026]

# 1. Converter colunas de data para datetime
for ano in anos:
    df = dataframes[ano]
    df['compra'] = pd.to_datetime(df['compra'], format='%d/%m/%Y', errors='coerce')
    df['insercao'] = pd.to_datetime(df['insercao'], format='%d/%m/%Y', errors='coerce')
    print(f"✅ {ano}: colunas de data convertidas para datetime")

# 2. Converter códigos para string (evitar que sejam tratados como números)
for ano in anos:
    df = dataframes[ano]
    df['codigo_br'] = df['codigo_br'].astype(str)
    print(f"✅ {ano}: coluna 'codigo_br' convertida para string")

print("\n📌 Todos os tipos de dados foram corrigidos!")

# ============================================
# Verificar tipos após correção
# ============================================

print("\n📌 VERIFICANDO TIPOS APÓS CORREÇÃO:\n")

for ano in anos:
    df = dataframes[ano]
    print(f"--- {ano} ---")
    print(f"  compra: {df['compra'].dtype}")
    print(f"  insercao: {df['insercao'].dtype}")
    print(f"  codigo_br: {df['codigo_br'].dtype}")
    print("-" * 30)

🔹 Corrigindo tipos de dados...
✅ 2020: colunas de data convertidas para datetime
✅ 2021: colunas de data convertidas para datetime
✅ 2022: colunas de data convertidas para datetime
✅ 2023: colunas de data convertidas para datetime
✅ 2024: colunas de data convertidas para datetime
✅ 2025: colunas de data convertidas para datetime
✅ 2026: colunas de data convertidas para datetime
✅ 2020: coluna 'codigo_br' convertida para string
✅ 2021: coluna 'codigo_br' convertida para string
✅ 2022: coluna 'codigo_br' convertida para string
✅ 2023: coluna 'codigo_br' convertida para string
✅ 2024: coluna 'codigo_br' convertida para string
✅ 2025: coluna 'codigo_br' convertida para string
✅ 2026: coluna 'codigo_br' convertida para string

📌 Todos os tipos de dados foram corrigidos!

📌 VERIFICANDO TIPOS APÓS CORREÇÃO:

--- 2020 ---
  compra: datetime64[us]
  insercao: datetime64[us]
  codigo_br: str
------------------------------
--- 2021 ---
  compra: datetime64[us]
  insercao: datetime64[us]
  codigo_br: str
------------------------------
--- 2022 ---
  compra: datetime64[us]
  insercao: datetime64[us]
  codigo_br: str
------------------------------
--- 2023 ---
  compra: datetime64[us]
  insercao: datetime64[us]
  codigo_br: str
------------------------------
--- 2024 ---
  compra: datetime64[us]
  insercao: datetime64[us]
  codigo_br: str
------------------------------
--- 2025 ---
  compra: datetime64[us]
  insercao: datetime64[us]
  codigo_br: str
------------------------------
--- 2026 ---
  compra: datetime64[us]
  insercao: datetime64[us]
  codigo_br: str
------------------------------

In [23]:
# ============================================
# SPRINT 2: Padronizar campos de data (ano a ano)
# ============================================

print("🔹 Padronizando campos de data ")

anos = [2020, 2021, 2022, 2023, 2024, 2025, 2026]

for ano in anos:
    df = dataframes[ano]
    
    # 1. Converter colunas para datetime
    df['compra'] = pd.to_datetime(df['compra'], format='%d/%m/%Y', errors='coerce')
    df['insercao'] = pd.to_datetime(df['insercao'], format='%d/%m/%Y', errors='coerce')
    
    # 2. Extrair componentes
    df['ano_compra'] = df['compra'].dt.year
    df['mes_compra'] = df['compra'].dt.month
    df['dia_compra'] = df['compra'].dt.day
    
    df['ano_insercao'] = df['insercao'].dt.year
    df['mes_insercao'] = df['insercao'].dt.month
    df['dia_insercao'] = df['insercao'].dt.day
    
    # 3. Estatísticas rápidas
    print(f"\n📌 {ano}:")
    print(f"   compra: {df['compra'].dtype} | período: {df['compra'].min()} a {df['compra'].max()}")
    print(f"   insercao: {df['insercao'].dtype} | nulos: {df['insercao'].isna().sum():,}")
    print(f"   ✅ Datas padronizadas")

print("\n✅ Padronização de datas concluída para todos os anos!")

🔹 Padronizando campos de data

📌 2020:
   compra: datetime64[us] | período: 2020-01-01 00:00:00 a 2020-12-31 00:00:00
   insercao: datetime64[us] | nulos: 0
   ✅ Datas padronizadas

📌 2021:
   compra: datetime64[us] | período: 2021-01-01 00:00:00 a 2021-12-31 00:00:00
   insercao: datetime64[us] | nulos: 0
   ✅ Datas padronizadas

📌 2022:
   compra: datetime64[us] | período: 2022-01-01 00:00:00 a 2022-12-30 00:00:00
   insercao: datetime64[us] | nulos: 120
   ✅ Datas padronizadas

📌 2023:
   compra: datetime64[us] | período: 2023-01-01 00:00:00 a 2023-12-30 00:00:00
   insercao: datetime64[us] | nulos: 716
   ✅ Datas padronizadas

📌 2024:
   compra: datetime64[us] | período: 2024-01-01 00:00:00 a 2024-12-30 00:00:00
   insercao: datetime64[us] | nulos: 1,292
   ✅ Datas padronizadas

📌 2025:
   compra: datetime64[us] | período: 2025-01-01 00:00:00 a 2025-12-30 00:00:00
   insercao: datetime64[us] | nulos: 0
   ✅ Datas padronizadas

📌 2026:
   compra: datetime64[us] | período: 2026-01-06 00:00:00 a 2026-03-05 00:00:00
   insercao: datetime64[us] | nulos: 0
   ✅ Datas padronizadas

✅ Padronização de datas concluída para todos os anos!

In [24]:
# ============================================
# SPRINT 2: Ajustar formatação de valores monetários e quantidades (ano a ano)
# ============================================

print("🔹 Ajustando formatação de valores monetários e quantidades...")

# Colunas a verificar
colunas_numericas = ['preco_unitario', 'preco_total', 'qtd_itens_comprados']
anos = [2020, 2021, 2022, 2023, 2024, 2025, 2026]

for ano in anos:
    df = dataframes[ano]
    print(f"\n📌 {ano}:")
    
    for col in colunas_numericas:
        if col in df.columns:
            # 1. Verificar se há vírgula como separador decimal (se for object)
            if df[col].dtype == 'object':
                print(f"   ⚠️ {col}: é 'object' (pode ter vírgula). Corrigindo...")
                df[col] = df[col].astype(str).str.replace(',', '.')
                df[col] = pd.to_numeric(df[col], errors='coerce')
                print(f"      ✅ {col} convertido para {df[col].dtype}")
            else:
                print(f"   ✅ {col}: {df[col].dtype} (formato correto)")
            
            # 2. Verificar valores inconsistentes (negativos e zeros)
            negativos = (df[col] < 0).sum()
            zeros = (df[col] == 0).sum()
            if negativos > 0:
                print(f"      ⚠️ {negativos:,} valores negativos")
            if zeros > 0:
                print(f"      ℹ️ {zeros:,} valores zero")
    
    # 3. Estatísticas rápidas
    print(f"   📊 Resumo {ano}:")
    for col in colunas_numericas:
        if col in df.columns:
            print(f"      {col}: min={df[col].min():.2f}, max={df[col].max():.2f}, média={df[col].mean():.2f}")

print("\n✅ Ajuste de formatação concluído para todos os anos!")

🔹 Ajustando formatação de valores monetários e quantidades...

📌 2020:
   ✅ preco_unitario: float64 (formato correto)
   ✅ preco_total: float64 (formato correto)
   ✅ qtd_itens_comprados: int64 (formato correto)
   📊 Resumo 2020:
      preco_unitario: min=0.00, max=255614.90, média=72.66
      preco_total: min=0.00, max=621600000.00, média=59500.40
      qtd_itens_comprados: min=1.00, max=487620000.00, média=103389.02

📌 2021:
   ✅ preco_unitario: float64 (formato correto)
   ✅ preco_total: float64 (formato correto)
   ✅ qtd_itens_comprados: int64 (formato correto)
   📊 Resumo 2021:
      preco_unitario: min=0.00, max=266097.60, média=62.76
      preco_total: min=0.00, max=484512000.00, média=88626.27
      qtd_itens_comprados: min=1.00, max=487620000.00, média=127833.77

📌 2022:
   ✅ preco_unitario: float64 (formato correto)
   ✅ preco_total: float64 (formato correto)
   ✅ qtd_itens_comprados: int64 (formato correto)
   📊 Resumo 2022:
      preco_unitario: min=0.00, max=495000.00, média=103.16
      preco_total: min=0.00, max=676524931.44, média=189506.32
      qtd_itens_comprados: min=1.00, max=819600000.00, média=170650.64

📌 2023:
   ✅ preco_unitario: float64 (formato correto)
   ✅ preco_total: float64 (formato correto)
   ✅ qtd_itens_comprados: int64 (formato correto)
   📊 Resumo 2023:
      preco_unitario: min=0.00, max=4804290.00, média=316.49
      preco_total: min=0.16, max=1364418360.00, média=153790.71
      qtd_itens_comprados: min=1.00, max=4356140000.00, média=318196.56

📌 2024:
   ✅ preco_unitario: float64 (formato correto)
   ✅ preco_total: float64 (formato correto)
   ✅ qtd_itens_comprados: int64 (formato correto)
   📊 Resumo 2024:
      preco_unitario: min=0.01, max=8191720.00, média=748.92
      preco_total: min=0.20, max=1662919160.00, média=341462.32
      qtd_itens_comprados: min=1.00, max=246874294.00, média=202869.84

📌 2025:
   ✅ preco_unitario: float64 (formato correto)
   ✅ preco_total: float64 (formato correto)
   ✅ qtd_itens_comprados: int64 (formato correto)
   📊 Resumo 2025:
      preco_unitario: min=0.00, max=639303.91, média=294.14
      preco_total: min=0.16, max=22816000000.00, média=1332477.47
      qtd_itens_comprados: min=1.00, max=135116376.00, média=255514.06

📌 2026:
   ✅ preco_unitario: float64 (formato correto)
   ✅ preco_total: float64 (formato correto)
   ✅ qtd_itens_comprados: int64 (formato correto)
   📊 Resumo 2026:
      preco_unitario: min=0.03, max=415789.90, média=748.32
      preco_total: min=8.80, max=126034028.09, média=512048.80
      qtd_itens_comprados: min=2.00, max=237800053.00, média=344571.72

✅ Ajuste de formatação concluído para todos os anos!

In [25]:
# ============================================
# SPRINT 2: Corrigir problemas de codificação de caracteres
# ============================================

print("🔹 Verificando codificação dos arquivos...")

# Lista de anos
anos = [2020, 2021, 2022, 2023, 2024, 2025, 2026]

# Recarregar os arquivos com encoding UTF-8 (caso necessário)
for ano in anos:
    try:
        # Se já estiver carregado, apenas verifica
        if ano in dataframes:
            print(f"✅ {ano}: já carregado. Codificação: UTF-8")
        else:
            # Se não estiver carregado, carrega com UTF-8
            dataframes[ano] = pd.read_csv(f'{ano}.csv', sep=';', encoding='utf-8')
            print(f"✅ {ano}: carregado com UTF-8")
    except Exception as e:
        print(f"❌ {ano}: erro ao carregar - {e}")

# Verificar se há caracteres problemáticos (opcional)
print("\n🔹 Verificando caracteres especiais em colunas de texto...")

colunas_texto = ['nome_instituicao', 'descricao_catmat', 'fornecedor', 'fabricante']
for col in colunas_texto:
    if col in dataframes[2020].columns:
        # Verificar se há caracteres que indicam erro de encoding
        for ano in anos:
            df = dataframes[ano]
            amostra = df[col].head(3).astype(str).tolist()
            for valor in amostra:
                if '�' in valor:
                    print(f"   ⚠️ Caractere suspeito em {col} no ano {ano}: {valor}")
                elif 'Ã' in valor or '�' in valor:
                    print(f"   ⚠️ Possível erro de encoding em {col} no ano {ano}: {valor}")

print("\n📌 Todos os arquivos estão com encoding UTF-8.")

🔹 Verificando codificação dos arquivos...
✅ 2020: já carregado. Codificação: UTF-8
✅ 2021: já carregado. Codificação: UTF-8
✅ 2022: já carregado. Codificação: UTF-8
✅ 2023: já carregado. Codificação: UTF-8
✅ 2024: já carregado. Codificação: UTF-8
✅ 2025: já carregado. Codificação: UTF-8
✅ 2026: já carregado. Codificação: UTF-8

🔹 Verificando caracteres especiais em colunas de texto...
   ⚠️ Possível erro de encoding em descricao_catmat no ano 2020: GLICONATO DE CÁLCIO, DOSAGEM:10%, APRESENTAÇÃO:SOLUÇÃO INJETÁVEL
   ⚠️ Possível erro de encoding em descricao_catmat no ano 2020: BOLSA VENTILAÇÃO PULMONAR, MATERIAL:BORRACHA, CAPACIDADE:1 L, APLICAÇÃO:VENTILAÇÃO / REINALAÇÃO
   ⚠️ Possível erro de encoding em descricao_catmat no ano 2021: BOLSA OSTOMIA, MATÉRIA PRIMA:PLáSTICO, APLICAÇÃO:COLOSTOMIA, NÚMERO DE PEÇAS:2 PEÇAS (PLACA E BOLSA SEPARADAS), MODELO:DRENÁVEL, TIPO DE BOLSA:OPACA, TIPO DE ADESIVO:ADESIVO MICROPOROSO, MATERIAL DA PLACA:RESINA SINTÉTICA, DIÂMETRO:RECORTÁVEL ATÉ 90 MM, CARACTERÍSTICAS ADICIONAIS:COM FILTRO DE CARVÃO ATIVADO
   ⚠️ Possível erro de encoding em descricao_catmat no ano 2021: ARTIGO PARA HIGIENE NO LEITO, TIPO:LUVA, MATERIAL:TECIDO 100% ALGODÃO, COMPONENTES:ATOALHADA
   ⚠️ Possível erro de encoding em descricao_catmat no ano 2022: BICARBONATO DE SÓDIO, CONCENTRAÇÃO:8,40%, FORMA FARMACÊUTICA:SOLUÇÃO INJETÁVEL, CARACTERÍSTICA ADICIONAL:EM SISTEMA FECHADO
   ⚠️ Possível erro de encoding em descricao_catmat no ano 2022: EPINEFRINA, CONCENTRAÇÃO:0,5 MG/ML, FORMA FARMACEUTICA:SOLUÇÃO INJETÁVEL, CARACTERÍSTICA ADICIONAL:COM CANETA APLICADORA
   ⚠️ Possível erro de encoding em descricao_catmat no ano 2022: CLORETO DE SÓDIO, CONCENTRAÇAO:0,9 %, FORMA FARMACEUTICA:SOLUÇÃO ESTÉRIL NÃO INJETÁVEL
   ⚠️ Possível erro de encoding em descricao_catmat no ano 2023: REAGENTE PARA DIAGNÓSTICO CLÍNICO 5, TIPO:ALBUMINA BOVINA, CARACTERÍSTICAS ADICIONAIS:SOLUÇÃO A 22%
   ⚠️ Possível erro de encoding em descricao_catmat no ano 2025: HIDROCORTISONA, COMPOSIÇÃO:SAL SUCCINATO SÓDICO, CONCENTRAÇÃO:500 MG, FORMA FARMACÊUTICA:PÓ LIÓFILO P/ INJETÁVEL
   ⚠️ Possível erro de encoding em descricao_catmat no ano 2025: METOCLOPRAMIDA CLORIDRATO, DOSAGEM:5 MG/ML, APRESENTAÇÃO:SOLUÇÃO INJETÁVEL
   ⚠️ Possível erro de encoding em descricao_catmat no ano 2026: TUBO ENDOBRONQUIAL, MODELO:DUPLO LÚMEN C/ GANCHO DE CARINA, TIPO USO:ESQUERDO, CALIBRE:35 FR, MATERIAL :LÁTEX NATURAL, COMPONENTES:C/ BALÃO TRAQUEAL E ENDOBRONQUIAL, CONECTOR:CONECTORES, ADICIONAL:SONDAS ASPIRAÇÃO, ADICIONAL :RADIOPACO, GRADUADO
   ⚠️ Possível erro de encoding em descricao_catmat no ano 2026: DESVENLAFAXINA, COMPOSIÇÃO:SAL SUCCINATO, CONCENTRAÇÃO:100 MG, FORMA FARMACÊUTICA:LIBERAÇÃO CONTROLADA
   ⚠️ Possível erro de encoding em descricao_catmat no ano 2026: NUSINERSENA, CONCENTRAÇÃO:2,4 MG/ML, FORMA FARMACÊUTICA:SOLUÇÃO INJETÁVEL

📌 Todos os arquivos estão com encoding UTF-8.

In [26]:
## ============================================
# SPRINT 2: Verificar nulos, vazios e inconsistentes 
# ============================================

print("🔹 Verificando valores nulos, vazios e inconsistentes \n")

anos = [2020, 2021, 2022, 2023, 2024, 2025, 2026]
resumo_anos = {}

for ano in anos:
    df = dataframes[ano]
    print(f"📌 {ano}:")
    
    # 1. Nulos por coluna (apenas com nulos > 0)
    nulos = df.isnull().sum()
    nulos = nulos[nulos > 0].sort_values(ascending=False)
    
    if len(nulos) > 0:
        print("   Nulos por coluna:")
        for col, qtd in nulos.items():
            print(f"      {col}: {qtd:,}")
    else:
        print("   ✅ Nenhum valor nulo encontrado.")
    
    # 2. Valores vazios em colunas de texto (object)
    colunas_texto = df.select_dtypes(include=['object']).columns
    vazios_ano = 0
    for col in colunas_texto:
        vazios = (df[col] == '').sum()
        if vazios > 0:
            print(f"   ⚠️ {col}: {vazios:,} valores vazios")
            vazios_ano += vazios
    if vazios_ano == 0:
        print("   ✅ Nenhum valor vazio encontrado.")
    
    # 3. Inconsistências numéricas
    colunas_numericas = ['preco_unitario', 'preco_total', 'qtd_itens_comprados']
    for col in colunas_numericas:
        if col in df.columns:
            negativos = (df[col] < 0).sum()
            zeros = (df[col] == 0).sum()
            if negativos > 0:
                print(f"   ⚠️ {col}: {negativos:,} valores negativos")
            if zeros > 0:
                print(f"   ℹ️ {col}: {zeros:,} valores zero")
            # Percentil 99 (outliers)
            q99 = df[col].quantile(0.99)
            if q99 > 0:
                print(f"   ℹ️ {col}: 99% dos valores estão abaixo de {q99:,.2f}")
    
    # 4. Inconsistências em datas
    if 'compra' in df.columns and 'insercao' in df.columns:
        data_invalida = (df['compra'] > df['insercao']).sum()
        if data_invalida > 0:
            print(f"   ⚠️ {data_invalida:,} registros com compra posterior à inserção")
        else:
            print("   ✅ Datas consistentes")
    
    # Armazenar resumo do ano
    resumo_anos[ano] = {
        'total_registros': len(df),
        'total_nulos': df.isnull().sum().sum(),
        'total_vazios': vazios_ano,
        'duplicados': df.duplicated().sum()
    }
    print("-" * 40)

# 5. Resumo geral
print("\n📌 RESUMO GERAL:")
total_registros = sum(r['total_registros'] for r in resumo_anos.values())
total_nulos = sum(r['total_nulos'] for r in resumo_anos.values())
total_vazios = sum(r['total_vazios'] for r in resumo_anos.values())
total_duplicados = sum(r['duplicados'] for r in resumo_anos.values())

print(f"   Total de registros (todos os anos): {total_registros:,}")
print(f"   Total de nulos: {total_nulos:,}")
print(f"   Total de valores vazios: {total_vazios:,}")
print(f"   Total de duplicados: {total_duplicados:,}")

print("\n✅ Verificação concluída para todos os anos!")

🔹 Verificando valores nulos, vazios e inconsistentes

📌 2020:
   Nulos por coluna:
      capacidade: 53,437
      unidade_medida: 53,437
      generico: 47,684
      anvisa: 47,684
      unidade_fornecimento: 6
      unidade_fornecimento_capacidade: 6
   ✅ Nenhum valor vazio encontrado.
   ℹ️ preco_unitario: 99% dos valores estão abaixo de 373.61
   ℹ️ preco_total: 99% dos valores estão abaixo de 549,410.49
   ℹ️ qtd_itens_comprados: 99% dos valores estão abaixo de 1,400,000.00
   ✅ Datas consistentes
----------------------------------------
📌 2021:
   Nulos por coluna:
      capacidade: 53,401
      unidade_medida: 53,401
      generico: 45,199
      anvisa: 45,199
      nome_instituicao: 8
      unidade_fornecimento: 4
      unidade_fornecimento_capacidade: 4
   ✅ Nenhum valor vazio encontrado.
   ℹ️ preco_unitario: 99% dos valores estão abaixo de 448.35
   ℹ️ preco_total: 99% dos valores estão abaixo de 990,140.77
   ℹ️ qtd_itens_comprados: 99% dos valores estão abaixo de 1,598,747.35
   ✅ Datas consistentes
----------------------------------------
📌 2022:
   Nulos por coluna:
      capacidade: 57,645
      unidade_medida: 57,645
      generico: 49,013
      anvisa: 49,013
      insercao: 120
      ano_insercao: 120
      mes_insercao: 120
      dia_insercao: 120
      unidade_fornecimento: 4
      unidade_fornecimento_capacidade: 4
   ✅ Nenhum valor vazio encontrado.
   ℹ️ preco_unitario: 99% dos valores estão abaixo de 890.17
   ℹ️ preco_total: 99% dos valores estão abaixo de 1,724,496.20
   ℹ️ qtd_itens_comprados: 99% dos valores estão abaixo de 1,800,000.00
   ✅ Datas consistentes
----------------------------------------
📌 2023:
   Nulos por coluna:
      capacidade: 19,821
      unidade_medida: 19,821
      generico: 14,587
      anvisa: 14,587
      insercao: 716
      ano_insercao: 716
      mes_insercao: 716
      dia_insercao: 716
      nome_instituicao: 13
   ✅ Nenhum valor vazio encontrado.
   ℹ️ preco_unitario: 99% dos valores estão abaixo de 1,035.66
   ℹ️ preco_total: 99% dos valores estão abaixo de 1,805,808.15
   ℹ️ qtd_itens_comprados: 99% dos valores estão abaixo de 2,100,666.90
   ⚠️ 1 registros com compra posterior à inserção
----------------------------------------
📌 2024:
   Nulos por coluna:
      capacidade: 16,708
      unidade_medida: 16,708
      generico: 8,674
      anvisa: 8,674
      insercao: 1,292
      ano_insercao: 1,292
      mes_insercao: 1,292
      dia_insercao: 1,292
      nome_instituicao: 77
      unidade_fornecimento: 3
      unidade_fornecimento_capacidade: 3
   ✅ Nenhum valor vazio encontrado.
   ℹ️ preco_unitario: 99% dos valores estão abaixo de 2,662.89
   ℹ️ preco_total: 99% dos valores estão abaixo de 3,030,973.78
   ℹ️ qtd_itens_comprados: 99% dos valores estão abaixo de 2,100,000.00
   ⚠️ 11 registros com compra posterior à inserção
----------------------------------------
📌 2025:
   Nulos por coluna:
      capacidade: 16,539
      unidade_medida: 16,539
      generico: 6,712
      anvisa: 6,712
      nome_instituicao: 59
      unidade_fornecimento: 8
      unidade_fornecimento_capacidade: 8
   ✅ Nenhum valor vazio encontrado.
   ℹ️ preco_unitario: 99% dos valores estão abaixo de 4,765.85
   ℹ️ preco_total: 99% dos valores estão abaixo de 5,872,055.70
   ℹ️ qtd_itens_comprados: 99% dos valores estão abaixo de 4,005,798.20
   ✅ Datas consistentes
----------------------------------------
📌 2026:
   Nulos por coluna:
      capacidade: 484
      unidade_medida: 484
      generico: 168
      anvisa: 168
   ✅ Nenhum valor vazio encontrado.
   ℹ️ preco_unitario: 99% dos valores estão abaixo de 4,754.64
   ℹ️ preco_total: 99% dos valores estão abaixo de 8,898,794.64
   ℹ️ qtd_itens_comprados: 99% dos valores estão abaixo de 1,467,102.80
   ✅ Datas consistentes
----------------------------------------

📌 RESUMO GERAL:
   Total de registros (todos os anos): 342,716
   Total de nulos: 788,863
   Total de valores vazios: 0
   Total de duplicados: 19

✅ Verificação concluída para todos os anos!

In [27]:
# ============================================
# SPRINT 2 TRATAMENTO DE NULOS (coluna generico) 
# ============================================

def preencher_generico_3var(df):
    """Preenche nulos de 'generico' usando a moda por grupo de 3 variáveis."""
    nulos_iniciais = df['generico'].isna().sum()
    print(f"🔹 Nulos iniciais: {nulos_iniciais}")

    df = df.copy()
    df['chave'] = (
        df['descricao_catmat'].fillna('NaN').astype(str) + ' || ' +
        df['unidade_fornecimento'].fillna('NaN').astype(str) + ' || ' +
        df['fornecedor'].fillna('NaN').astype(str)
    )

    moda_por_grupo = {}
    for chave, grupo in df.groupby('chave'):
        valores = grupo['generico'].dropna()
        if len(valores) > 0:
            moda_por_grupo[chave] = valores.mode()[0]

    df['generico'] = df.apply(
        lambda row: moda_por_grupo.get(row['chave'], row['generico'])
        if pd.isna(row['generico']) else row['generico'],
        axis=1
    )
    df = df.drop(columns=['chave'])

    nulos_finais = df['generico'].isna().sum()
    print(f"✅ Nulos preenchidos (3 var): {nulos_iniciais - nulos_finais}")
    print(f"📌 Nulos restantes: {nulos_finais}")
    return df


def preencher_nao_informado_com_extras(df, colunas_extras=['capacidade', 'unidade_medida', 'fabricante'], limiar_confianca=0.8):
    """Substitui 'Não Informado' com base em colunas extras, se atingir o limiar."""
    mask_nao_informado = df['generico'] == 'Não Informado'
    if not mask_nao_informado.any():
        print("✅ Nenhum 'Não Informado' para processar.")
        return df

    print(f"🔹 'Não Informado' iniciais: {mask_nao_informado.sum()}")

    colunas_base = ['descricao_catmat', 'unidade_fornecimento', 'fornecedor']
    colunas_agrupamento = colunas_base + colunas_extras
    colunas_existentes = [col for col in colunas_agrupamento if col in df.columns]
    if len(colunas_existentes) < len(colunas_agrupamento):
        print(f"⚠️ Colunas não encontradas: {set(colunas_agrupamento) - set(colunas_existentes)}")
        colunas_agrupamento = colunas_existentes

    df['chave'] = df[colunas_agrupamento].fillna('NaN').astype(str).agg(' || '.join, axis=1)

    df_referencia = df[~mask_nao_informado].copy()
    proporcoes = df_referencia.groupby('chave')['generico'].value_counts(normalize=True).unstack().fillna(0)

    mapa_preenchimento = {}
    for chave in df.loc[mask_nao_informado, 'chave'].unique():
        if chave in proporcoes.index:
            prop_s = proporcoes.loc[chave].get('S', 0)
            prop_n = proporcoes.loc[chave].get('N', 0)
            if prop_s >= limiar_confianca:
                mapa_preenchimento[chave] = 'S'
            elif prop_n >= limiar_confianca:
                mapa_preenchimento[chave] = 'N'

    df.loc[mask_nao_informado, 'generico'] = df.loc[mask_nao_informado].apply(
        lambda row: mapa_preenchimento.get(row['chave'], row['generico']),
        axis=1
    )
    df = df.drop(columns=['chave'])

    preenchidos = (mask_nao_informado & (df['generico'] != 'Não Informado')).sum()
    print(f"✅ Preenchidos com extras: {preenchidos}")
    print(f"📌 Ainda 'Não Informado': {(df['generico'] == 'Não Informado').sum()}")
    return df


def tratar_coluna_generico(df):
    """Aplica as duas etapas de tratamento na coluna 'generico'."""
    df = preencher_generico_3var(df)
    df['generico'] = df['generico'].fillna('Não Informado')
    df = preencher_nao_informado_com_extras(df)
    return df


def analise_descritiva_generico(df, ano):
    """Exibe análise descritiva da coluna 'generico' para um ano específico."""
    contagem = df['generico'].value_counts()
    percentual = (contagem / len(df) * 100).round(2)
    resumo = pd.DataFrame({
        'Categoria': contagem.index,
        'Quantidade': contagem.values,
        'Percentual (%)': percentual.values
    })
    print("="*50)
    print(f"ANÁLISE DESCRITIVA - {ano} - COLUNA 'generico'")
    print("="*50)
    print(resumo.to_string(index=False))
    print(f"\nTotal de registros: {len(df):,}")
    print(f"Total preenchido (S + N): {contagem.get('S', 0) + contagem.get('N', 0):,}")
    print(f"Total 'Não Informado': {contagem.get('Não Informado', 0):,}")
    print("-"*50)

    # ============================================
# EXECUÇÃO PARA TODOS OS ANOS
# ============================================

anos = [2020, 2021, 2022, 2023, 2024, 2025, 2026]

# Caso você já tenha os dataframes carregados em um dicionário chamado 'dataframes'
for ano in anos:
    if ano in dataframes:
        print(f"\n{'='*60}")
        print(f"🔹 PROCESSANDO ANO {ano}")
        print(f"{'='*60}")
        df = dataframes[ano].copy()          # cópia para não alterar o original
        df = tratar_coluna_generico(df)      # aplica o tratamento
        analise_descritiva_generico(df, ano) # exibe o resumo
        dataframes[ano] = df                 # (opcional) atualiza o dicionário
        # df.to_csv(f"{ano}_tratado.csv", index=False)  # (opcional) salvar
    else:
        print(f"⚠️ Ano {ano} não encontrado no dicionário 'dataframes'.")

============================================================
🔹 PROCESSANDO ANO 2020
============================================================
🔹 Nulos iniciais: 47684
✅ Nulos preenchidos (3 var): 8490
📌 Nulos restantes: 39194
🔹 'Não Informado' iniciais: 39194
✅ Preenchidos com extras: 0
📌 Ainda 'Não Informado': 39194
==================================================
ANÁLISE DESCRITIVA - 2020 - COLUNA 'generico'
==================================================
    Categoria  Quantidade  Percentual (%)
Não Informado       39194           46.21
            S       27174           32.04
            N       18451           21.75

Total de registros: 84,819
Total preenchido (S + N): 45,625
Total 'Não Informado': 39,194
--------------------------------------------------

============================================================
🔹 PROCESSANDO ANO 2021
============================================================
🔹 Nulos iniciais: 45199
✅ Nulos preenchidos (3 var): 7017
📌 Nulos restantes: 38182
🔹 'Não Informado' iniciais: 38182
✅ Preenchidos com extras: 0
📌 Ainda 'Não Informado': 38182
==================================================
ANÁLISE DESCRITIVA - 2021 - COLUNA 'generico'
==================================================
    Categoria  Quantidade  Percentual (%)
Não Informado       38182           45.66
            S       26155           31.28
            N       19285           23.06

Total de registros: 83,622
Total preenchido (S + N): 45,440
Total 'Não Informado': 38,182
--------------------------------------------------

============================================================
🔹 PROCESSANDO ANO 2022
============================================================
🔹 Nulos iniciais: 49013
✅ Nulos preenchidos (3 var): 7654
📌 Nulos restantes: 41359
🔹 'Não Informado' iniciais: 41359
✅ Preenchidos com extras: 0
📌 Ainda 'Não Informado': 41359
==================================================
ANÁLISE DESCRITIVA - 2022 - COLUNA 'generico'
==================================================
    Categoria  Quantidade  Percentual (%)
Não Informado       41359           46.48
            S       25050           28.15
            N       22582           25.38

Total de registros: 88,991
Total preenchido (S + N): 47,632
Total 'Não Informado': 41,359
--------------------------------------------------

============================================================
🔹 PROCESSANDO ANO 2023
============================================================
🔹 Nulos iniciais: 14587
✅ Nulos preenchidos (3 var): 1702
📌 Nulos restantes: 12885
🔹 'Não Informado' iniciais: 12885
✅ Preenchidos com extras: 0
📌 Ainda 'Não Informado': 12885
==================================================
ANÁLISE DESCRITIVA - 2023 - COLUNA 'generico'
==================================================
    Categoria  Quantidade  Percentual (%)
Não Informado       12885           40.28
            S       11876           37.12
            N        7231           22.60

Total de registros: 31,992
Total preenchido (S + N): 19,107
Total 'Não Informado': 12,885
--------------------------------------------------

============================================================
🔹 PROCESSANDO ANO 2024
============================================================
🔹 Nulos iniciais: 8674
✅ Nulos preenchidos (3 var): 1537
📌 Nulos restantes: 7137
🔹 'Não Informado' iniciais: 7137
✅ Preenchidos com extras: 0
📌 Ainda 'Não Informado': 7137
==================================================
ANÁLISE DESCRITIVA - 2024 - COLUNA 'generico'
==================================================
    Categoria  Quantidade  Percentual (%)
            N        9598           36.55
            S        9523           36.27
Não Informado        7137           27.18

Total de registros: 26,258
Total preenchido (S + N): 19,121
Total 'Não Informado': 7,137
--------------------------------------------------

============================================================
🔹 PROCESSANDO ANO 2025
============================================================
🔹 Nulos iniciais: 6712
✅ Nulos preenchidos (3 var): 512
📌 Nulos restantes: 6200
🔹 'Não Informado' iniciais: 6200
✅ Preenchidos com extras: 0
📌 Ainda 'Não Informado': 6200
==================================================
ANÁLISE DESCRITIVA - 2025 - COLUNA 'generico'
==================================================
    Categoria  Quantidade  Percentual (%)
            N       10465           39.92
            S        9550           36.43
Não Informado        6200           23.65

Total de registros: 26,215
Total preenchido (S + N): 20,015
Total 'Não Informado': 6,200
--------------------------------------------------

============================================================
🔹 PROCESSANDO ANO 2026
============================================================
🔹 Nulos iniciais: 168
✅ Nulos preenchidos (3 var): 0
📌 Nulos restantes: 168
🔹 'Não Informado' iniciais: 168
✅ Preenchidos com extras: 0
📌 Ainda 'Não Informado': 168
==================================================
ANÁLISE DESCRITIVA - 2026 - COLUNA 'generico'
==================================================
    Categoria  Quantidade  Percentual (%)
            N         336           41.03
            S         315           38.46
Não Informado         168           20.51

Total de registros: 819
Total preenchido (S + N): 651
Total 'Não Informado': 168
--------------------------------------------------

In [28]:
# ============================================
# SPRINT 2: TRATAMENTO COMPLETO DE DUPLICATAS
# ============================================

def tratar_duplicados(df, ano, colunas_parciais, colunas_contexto, top_n=3):
    """
    Executa o tratamento COMPLETO de duplicatas em um DataFrame de um único ano:
      FASE 1 → Avaliar duplicatas (completas + parciais)
      FASE 2 → Diagnosticar os maiores grupos com contexto
      FASE 3 → Classificar cada linha (unico / duplicata_real / compra_repetida)
      FASE 4 → Remover apenas 'duplicata_real', preservando compras repetidas legítimas
    
    Parâmetros:
        df: DataFrame do ano
        ano: int (para exibição)
        colunas_parciais: lista de colunas que formam a chave da duplicata
        colunas_contexto: colunas que diferenciam compras legítimas (data, instituição, etc.)
        top_n: quantos grupos mostrar no diagnóstico
    
    Retorna:
        df_limpo (DataFrame sem duplicatas reais) e um dict com o resumo.
    """
    
    # ============================================================
    # FASE 1: AVALIAR DUPLICATAS (COMPLETAS + PARCIAIS)
    # ============================================================
    print("="*60)
    print(f"📌 ANÁLISE DE DUPLICATAS - ANO {ano}")
    print("="*60)
    
    total_registros = len(df)
    print(f"Total de registros: {total_registros:,}")
    
    # 1.1 Duplicatas completas (todas as colunas)
    duplicados_completos = df.duplicated(keep=False)
    qtd_duplicados_completos = duplicados_completos.sum()
    qtd_linhas_unicas = total_registros - qtd_duplicados_completos
    
    print(f"\n🔹 DUPLICATAS COMPLETAS (todas as colunas):")
    print(f"   Registros duplicados: {qtd_duplicados_completos:,} ({qtd_duplicados_completos/total_registros*100:.2f}%)")
    print(f"   Registros únicos: {qtd_linhas_unicas:,}")
    
    if qtd_duplicados_completos > 0:
        amostra = df[duplicados_completos].head(5)
        print("\n   Exemplo de registros duplicados (primeiros 5):")
        print(amostra.to_string(index=False))
    
    # 1.2 Duplicatas parciais
    colunas_existentes = [c for c in colunas_parciais if c in df.columns]
    qtd_dup_parcial = 0
    if colunas_existentes:
        print(f"\n🔹 DUPLICATAS PARCIAIS (baseado em: {colunas_existentes}):")
        duplicados_parciais = df.duplicated(subset=colunas_existentes, keep=False)
        qtd_dup_parcial = duplicados_parciais.sum()
        print(f"   Registros com duplicatas parciais: {qtd_dup_parcial:,} ({qtd_dup_parcial/total_registros*100:.2f}%)")
        
        grupos = df.groupby(colunas_existentes).size()
        grupos_duplicados = grupos[grupos > 1]
        print(f"   Número de grupos duplicados: {len(grupos_duplicados):,}")
        
        if len(grupos_duplicados) > 0:
            print("\n   Maiores grupos de duplicatas parciais (top 5):")
            for idx, (keys, count) in enumerate(grupos_duplicados.nlargest(5).items()):
                keys_str = ' | '.join(str(k) for k in keys) if isinstance(keys, tuple) else str(keys)
                print(f"      {idx+1}. {keys_str[:120]} -> {count} registros")
    else:
        print("\n⚠️ Nenhuma das colunas parciais especificadas existe no DataFrame.")
    
    print(f"\n📊 RESUMO FASE 1:")
    print(f"   Total registros: {total_registros:,}")
    print(f"   Duplicatas completas: {qtd_duplicados_completos:,}")
    print(f"   Duplicatas parciais: {qtd_dup_parcial:,}")
    print("-"*60)
    
    # ============================================================
    # FASE 2: DIAGNÓSTICO DOS MAIORES GRUPOS (COM CONTEXTO)
    # ============================================================
    print("="*60)
    print(f"🔍 DIAGNÓSTICO DOS GRUPOS - ANO {ano}")
    print("="*60)
    
    ctx_existentes = [c for c in colunas_contexto if c in df.columns]
    
    if colunas_existentes:
        grupos = [(k, g) for k, g in df.groupby(colunas_existentes, dropna=False) if len(g) > 1]
        
        if not grupos:
            print(f"   ✅ Ano {ano}: nenhum grupo duplicado encontrado.")
        else:
            grupos.sort(key=lambda x: len(x[1]), reverse=True)
            print(f"   📌 Total de grupos duplicados: {len(grupos):,}")
            print(f"   📌 Mostrando os {top_n} maiores grupos:\n")
            
            for i, (chave, grupo) in enumerate(grupos[:top_n]):
                print("-"*60)
                print(f"🔹 GRUPO #{i+1} — {len(grupo)} registros")
                chave_str = ' | '.join(str(k)[:50] for k in chave) if isinstance(chave, tuple) else str(chave)[:100]
                print(f"   Chave: {chave_str}")
                
                cols_mostrar = colunas_existentes[:1] + ctx_existentes
                display_df = grupo[cols_mostrar].head(3).copy()
                for col in display_df.columns:
                    if display_df[col].dtype == 'object':
                        display_df[col] = display_df[col].astype(str).str.slice(0, 35)
                print(display_df.to_string(index=False))
                
                if len(grupo.drop_duplicates()) == 1:
                    print("   ⚠️  → DUPLICATA COMPLETA")
                else:
                    difs = [c for c in ctx_existentes if grupo[c].nunique(dropna=False) > 1]
                    if difs:
                        print(f"   💡 → COMPRA REPETIDA LEGÍTIMA (diferenças em: {difs})")
                    else:
                        print("   ⚠️  → PROVÁVEL DUPLICATA (contexto idêntico)")
            print("-"*60)
    
    # ============================================================
    # FASE 3: CLASSIFICAR CADA LINHA
    # ============================================================
    print("="*60)
    print(f"🏷️ CLASSIFICAÇÃO DE DUPLICATAS - ANO {ano}")
    print("="*60)
    
    df = df.copy()
    df['_classificacao'] = 'unico'
    
    if colunas_existentes:
        dup_mask = df.duplicated(subset=colunas_existentes, keep=False)
        
        for chave, grupo in df[dup_mask].groupby(colunas_existentes, dropna=False):
            idx = grupo.index
            
            # Se todas as colunas idênticas → duplicata real
            if len(df.loc[idx].drop_duplicates()) == 1:
                df.loc[idx, '_classificacao'] = 'duplicata_real'
                continue
            
            # Se há diferença em contexto → compra repetida
            dif_contexto = any(
                df.loc[idx, c].nunique(dropna=False) > 1
                for c in ctx_existentes if c in df.columns
            )
            df.loc[idx, '_classificacao'] = 'compra_repetida' if dif_contexto else 'duplicata_real'
    
    print("📊 Distribuição das classificações:")
    print(df['_classificacao'].value_counts().to_string())
    print("-"*60)
    
    # ============================================================
    # FASE 4: REMOVER APENAS DUPLICATAS REAIS
    # ============================================================
    print("="*60)
    print(f"🗑️ REMOÇÃO DE DUPLICATAS REAIS - ANO {ano}")
    print("="*60)
    
    antes = len(df)
    df_limpo = df[df['_classificacao'] != 'duplicata_real'].copy()
    df_limpo = df_limpo.drop(columns=['_classificacao'])
    removidos = antes - len(df_limpo)
    
    print(f"   Antes:     {antes:,} registros")
    print(f"   Depois:    {len(df_limpo):,} registros")
    print(f"   Removidos: {removidos:,} ({removidos/antes*100:.2f}%)")
    print(f"   Preservados como 'compra_repetida': {(df['_classificacao'] == 'compra_repetida').sum():,}")
    print("-"*60)
    
    # Resumo final do ano
    resumo = {
        'ano': ano,
        'total_registros': total_registros,
        'duplicados_completos': qtd_duplicados_completos,
        'duplicados_parciais': qtd_dup_parcial,
        'removidos': removidos,
        'total_final': len(df_limpo)
    }
    
    return df_limpo, resumo


# ============================================
# EXECUÇÃO (FORA DA FUNÇÃO — SEM INDENTAÇÃO)
# ============================================

anos = [2020, 2021, 2022, 2023, 2024, 2025, 2026]

colunas_para_parciais = ['descricao_catmat', 'fornecedor', 'preco_total', 'qtd_itens_comprados']
colunas_contexto = ['compra', 'insercao', 'cnpj_instituicao', 'codigo_br',
                    'nome_instituicao', 'modalidade_compra']

resumos = []

for ano in anos:
    if ano in dataframes:
        print("\n" + "#"*60)
        print(f"# PROCESSANDO ANO {ano}")
        print("#"*60)
        df_limpo, resumo = tratar_duplicados(
            dataframes[ano], ano,
            colunas_parciais=colunas_para_parciais,
            colunas_contexto=colunas_contexto,
            top_n=3
        )
        dataframes[ano] = df_limpo
        resumos.append(resumo)
    else:
        print(f"⚠️ Ano {ano} não encontrado.")

# Resumo consolidado final
print("\n" + "="*60)
print("📋 RESUMO CONSOLIDADO — DUPLICATAS")
print("="*60)
df_resumo = pd.DataFrame(resumos)
print(df_resumo.to_string(index=False))
print("="*60)

############################################################
# PROCESSANDO ANO 2020
############################################################
============================================================
📌 ANÁLISE DE DUPLICATAS - ANO 2020
============================================================
Total de registros: 84,819

🔹 DUPLICATAS COMPLETAS (todas as colunas):
   Registros duplicados: 0 (0.00%)
   Registros únicos: 84,819

🔹 DUPLICATAS PARCIAIS (baseado em: ['descricao_catmat', 'fornecedor', 'preco_total', 'qtd_itens_comprados']):
   Registros com duplicatas parciais: 1,009 (1.19%)
   Número de grupos duplicados: 490

   Maiores grupos de duplicatas parciais (top 5):
      1. CLORPROMAZINA, DOSAGEM:25 MG | CRISTALIA PRODUTOS QUIMICOS FARMACEUTICOS LTDA | 9500.0 | 50000 -> 4 registros
      2. IMIPRAMINA, PRINCÍPIO ATIVO:CLORIDRATO, DOSAGEM:25 MG | CRISTALIA PRODUTOS QUIMICOS FARMACEUTICOS LTDA | 10800.0 | 40000 -> 4 registros
      3. MORFINA, APRESENTAÇÃO:SULFATO, CONCENTRAÇÃO:10MG/ML, FORMA FARMACÊUTICA:SOLUÇÃO INJETÁVEL | CRISTALIA PRODUTOS QUIMICOS  -> 4 registros
      4. MORFINA, APRESENTAÇÃO:SULFATO, CONCENTRAÇÃO:10MG/ML, FORMA FARMACÊUTICA:SOLUÇÃO INJETÁVEL | CRISTALIA PRODUTOS QUIMICOS  -> 4 registros
      5. PIRIMETAMINA, DOSAGEM:25 MG | PROMEFARMA MEDICAMENTOS E PRODUTOS HOSPITALARES LTDA | 35.0 | 500 -> 4 registros

📊 RESUMO FASE 1:
   Total registros: 84,819
   Duplicatas completas: 0
   Duplicatas parciais: 1,009
------------------------------------------------------------
============================================================
🔍 DIAGNÓSTICO DOS GRUPOS - ANO 2020
============================================================
   📌 Total de grupos duplicados: 490
   📌 Mostrando os 3 maiores grupos:

------------------------------------------------------------
🔹 GRUPO #1 — 4 registros
   Chave: CLORPROMAZINA, DOSAGEM:25 MG | CRISTALIA PRODUTOS QUIMICOS FARMACEUTICOS LTDA | 9500.0 | 50000
            descricao_catmat     compra   insercao   cnpj_instituicao codigo_br                    nome_instituicao modalidade_compra
CLORPROMAZINA, DOSAGEM:25 MG 2020-03-25 2020-04-03 11.706.451/0001-65    267635 FUNDO MUNICIPAL DE SAUDE -PAROBE/RS            Pregão
CLORPROMAZINA, DOSAGEM:25 MG 2020-05-25 2020-06-23 77.816.510/0001-66    267635      MUNICIPIO DE FRANCISCO BELTRAO            Pregão
CLORPROMAZINA, DOSAGEM:25 MG 2020-06-17 2020-08-17 44.880.060/0001-11    267635                MUNICIPIO DE DRACENA            Pregão
   💡 → COMPRA REPETIDA LEGÍTIMA (diferenças em: ['compra', 'insercao', 'cnpj_instituicao', 'nome_instituicao'])
------------------------------------------------------------
🔹 GRUPO #2 — 4 registros
   Chave: IMIPRAMINA, PRINCÍPIO ATIVO:CLORIDRATO, DOSAGEM:25 | CRISTALIA PRODUTOS QUIMICOS FARMACEUTICOS LTDA | 10800.0 | 40000
                                     descricao_catmat     compra   insercao   cnpj_instituicao codigo_br                                 nome_instituicao modalidade_compra
IMIPRAMINA, PRINCÍPIO ATIVO:CLORIDRATO, DOSAGEM:25 MG 2020-01-14 2020-07-30 13.659.627/0001-09    267292 FUNDO MUNICIPAL DE SAUDE DE SAO GABRIEL DO OESTE            Pregão
IMIPRAMINA, PRINCÍPIO ATIVO:CLORIDRATO, DOSAGEM:25 MG 2020-01-14 2020-07-30 13.659.627/0001-09    267292 FUNDO MUNICIPAL DE SAUDE DE SAO GABRIEL DO OESTE            Pregão
IMIPRAMINA, PRINCÍPIO ATIVO:CLORIDRATO, DOSAGEM:25 MG 2020-03-13 2020-03-18 46.523.262/0001-31    267292                           MUNICIPIO DE GUARAREMA            Pregão
   💡 → COMPRA REPETIDA LEGÍTIMA (diferenças em: ['compra', 'insercao', 'cnpj_instituicao', 'nome_instituicao'])
------------------------------------------------------------
🔹 GRUPO #3 — 4 registros
   Chave: MORFINA, APRESENTAÇÃO:SULFATO, CONCENTRAÇÃO:10MG/M | CRISTALIA PRODUTOS QUIMICOS FARMACEUTICOS LTDA | 446.0 | 200
                                                                         descricao_catmat     compra   insercao   cnpj_instituicao codigo_br                                 nome_instituicao     modalidade_compra
MORFINA, APRESENTAÇÃO:SULFATO, CONCENTRAÇÃO:10MG/ML, FORMA FARMACÊUTICA:SOLUÇÃO INJETÁVEL 2020-01-14 2020-07-30 13.659.627/0001-09    304871 FUNDO MUNICIPAL DE SAUDE DE SAO GABRIEL DO OESTE                Pregão
MORFINA, APRESENTAÇÃO:SULFATO, CONCENTRAÇÃO:10MG/ML, FORMA FARMACÊUTICA:SOLUÇÃO INJETÁVEL 2020-03-12 2021-08-25 76.020.452/0001-05    304871                                MUNICIPIO DA LAPA Dispensa de Licitação
MORFINA, APRESENTAÇÃO:SULFATO, CONCENTRAÇÃO:10MG/ML, FORMA FARMACÊUTICA:SOLUÇÃO INJETÁVEL 2020-03-30 2020-10-22 11.356.696/0001-00    304871           FUNDO MUNICIPAL DE SAUDE DE SAO MATEUS                Pregão
   💡 → COMPRA REPETIDA LEGÍTIMA (diferenças em: ['compra', 'insercao', 'cnpj_instituicao', 'nome_instituicao', 'modalidade_compra'])
------------------------------------------------------------
============================================================
🏷️ CLASSIFICAÇÃO DE DUPLICATAS - ANO 2020
============================================================
📊 Distribuição das classificações:
_classificacao
unico              83810
compra_repetida      879
duplicata_real       130
------------------------------------------------------------
============================================================
🗑️ REMOÇÃO DE DUPLICATAS REAIS - ANO 2020
============================================================
   Antes:     84,819 registros
   Depois:    84,689 registros
   Removidos: 130 (0.15%)
   Preservados como 'compra_repetida': 879
------------------------------------------------------------

############################################################
# PROCESSANDO ANO 2021
############################################################
============================================================
📌 ANÁLISE DE DUPLICATAS - ANO 2021
============================================================
Total de registros: 83,622

🔹 DUPLICATAS COMPLETAS (todas as colunas):
   Registros duplicados: 0 (0.00%)
   Registros únicos: 83,622

🔹 DUPLICATAS PARCIAIS (baseado em: ['descricao_catmat', 'fornecedor', 'preco_total', 'qtd_itens_comprados']):
   Registros com duplicatas parciais: 1,219 (1.46%)
   Número de grupos duplicados: 604

   Maiores grupos de duplicatas parciais (top 5):
      1. ACEBROFILINA, CONCENTRAÇÃO:10 MG/ML, FORMA FARMACEUTICA:XAROPE | DISTRIBUIDORA DE MEDICAMENTOS SAUDE & VIDA LTDA | 1685. -> 3 registros
      2. AGULHA HIPODÉRMICA, MATERIAL:AÇO INOXIDÁVEL SILICONIZADO, DIMENSÃO:22 G X 1", TIPO PONTA:BISEL CURTO TRIFACETADO, TIPO C -> 3 registros
      3. BIPERIDENO, APRESENTAÇÃO:LACTATO, DOSAGEM:5 MG/ML, INDICAÇÃO:SOLUÇÃO INJETÁVEL | CRISTALIA PRODUTOS QUIMICOS FARMACEUTIC -> 3 registros
      4. CETOCONAZOL, DOSAGEM:20 MG/G, FORMA FARMACÊUTICA:CREME TÓPICO | DISTRIBUIDORA DE MEDICAMENTOS SAUDE & VIDA LTDA | 3227.0 -> 3 registros
      5. DIETA INFANTIL, INDICAÇÃO:0 A 12 MESES, ASPECTO FÍSICO:PÓ, USO:ENTERAL OU ORAL, FONTE DE PROTEÍNA:PTN ISOLADA SOJA, FONT -> 3 registros

📊 RESUMO FASE 1:
   Total registros: 83,622
   Duplicatas completas: 0
   Duplicatas parciais: 1,219
------------------------------------------------------------
============================================================
🔍 DIAGNÓSTICO DOS GRUPOS - ANO 2021
============================================================
   📌 Total de grupos duplicados: 604
   📌 Mostrando os 3 maiores grupos:

------------------------------------------------------------
🔹 GRUPO #1 — 3 registros
   Chave: ACEBROFILINA, CONCENTRAÇÃO:10 MG/ML, FORMA FARMACE | DISTRIBUIDORA DE MEDICAMENTOS SAUDE & VIDA LTDA | 1685.0 | 250
                                              descricao_catmat     compra   insercao   cnpj_instituicao codigo_br                                   nome_instituicao modalidade_compra
ACEBROFILINA, CONCENTRAÇÃO:10 MG/ML, FORMA FARMACEUTICA:XAROPE 2021-07-08 2022-02-04 06.554.323/0001-03    448839                            MUNICIPIO DE ALTO LONGA            Pregão
ACEBROFILINA, CONCENTRAÇÃO:10 MG/ML, FORMA FARMACEUTICA:XAROPE 2021-07-08 2022-02-04 06.554.323/0001-03    448839                            MUNICIPIO DE ALTO LONGA            Pregão
ACEBROFILINA, CONCENTRAÇÃO:10 MG/ML, FORMA FARMACEUTICA:XAROPE 2021-07-19 2022-04-30 02.419.781/0001-89    448839 MUNICIPIO DE PORTO - SECRETARIA MUNICIPAL DE SAUDE            Pregão
   💡 → COMPRA REPETIDA LEGÍTIMA (diferenças em: ['compra', 'insercao', 'cnpj_instituicao', 'nome_instituicao'])
------------------------------------------------------------
🔹 GRUPO #2 — 3 registros
   Chave: AGULHA HIPODÉRMICA, MATERIAL:AÇO INOXIDÁVEL SILICO | CENTERMEDI-COMERCIO DE PRODUTOS HOSPITALARES LTDA | 4200.0 | 500
                                                                                                                                                                                                                                          descricao_catmat     compra   insercao   cnpj_instituicao codigo_br      nome_instituicao modalidade_compra
AGULHA HIPODÉRMICA, MATERIAL:AÇO INOXIDÁVEL SILICONIZADO, DIMENSÃO:22 G X 1", TIPO PONTA:BISEL CURTO TRIFACETADO, TIPO CONEXÃO:CONECTOR LUER LOCK OU SLIP EM PLÁSTICO, TIPO FIXAÇÃO:PROTETOR PLÁSTICO, TIPO USO:ESTÉRIL, DESCARTÁVEL, EMBALAGEM INDIVIDUAL 2021-11-12 2022-09-22 76.282.680/0001-45    439807 MUNICIPIO DE MARIALVA            Pregão
AGULHA HIPODÉRMICA, MATERIAL:AÇO INOXIDÁVEL SILICONIZADO, DIMENSÃO:22 G X 1", TIPO PONTA:BISEL CURTO TRIFACETADO, TIPO CONEXÃO:CONECTOR LUER LOCK OU SLIP EM PLÁSTICO, TIPO FIXAÇÃO:PROTETOR PLÁSTICO, TIPO USO:ESTÉRIL, DESCARTÁVEL, EMBALAGEM INDIVIDUAL 2021-12-16 2022-09-22 76.282.680/0001-45    439807 MUNICIPIO DE MARIALVA            Pregão
AGULHA HIPODÉRMICA, MATERIAL:AÇO INOXIDÁVEL SILICONIZADO, DIMENSÃO:22 G X 1", TIPO PONTA:BISEL CURTO TRIFACETADO, TIPO CONEXÃO:CONECTOR LUER LOCK OU SLIP EM PLÁSTICO, TIPO FIXAÇÃO:PROTETOR PLÁSTICO, TIPO USO:ESTÉRIL, DESCARTÁVEL, EMBALAGEM INDIVIDUAL 2021-12-20 2022-08-10 76.282.680/0001-45    439807 MUNICIPIO DE MARIALVA            Pregão
   💡 → COMPRA REPETIDA LEGÍTIMA (diferenças em: ['compra', 'insercao'])
------------------------------------------------------------
🔹 GRUPO #3 — 3 registros
   Chave: BIPERIDENO, APRESENTAÇÃO:LACTATO, DOSAGEM:5 MG/ML, | CRISTALIA PRODUTOS QUIMICOS FARMACEUTICOS LTDA | 618.0 | 300
                                                              descricao_catmat     compra   insercao   cnpj_instituicao codigo_br                     nome_instituicao modalidade_compra
BIPERIDENO, APRESENTAÇÃO:LACTATO, DOSAGEM:5 MG/ML, INDICAÇÃO:SOLUÇÃO INJETÁVEL 2021-09-24 2022-09-27 46.522.983/0001-27    270138     MUNICIPIO DE SANTANA DE PARNAIBA            Pregão
BIPERIDENO, APRESENTAÇÃO:LACTATO, DOSAGEM:5 MG/ML, INDICAÇÃO:SOLUÇÃO INJETÁVEL 2021-11-30 2022-01-14 09.051.532/0001-22    270138 FUNDO MUNICIPAL DE SAUDE DE CASCAVEL            Pregão
BIPERIDENO, APRESENTAÇÃO:LACTATO, DOSAGEM:5 MG/ML, INDICAÇÃO:SOLUÇÃO INJETÁVEL 2021-12-30 2022-02-09 10.572.048/0002-09    270138                  SECRETARIA DE SAUDE            Pregão
   💡 → COMPRA REPETIDA LEGÍTIMA (diferenças em: ['compra', 'insercao', 'cnpj_instituicao', 'nome_instituicao'])
------------------------------------------------------------
============================================================
🏷️ CLASSIFICAÇÃO DE DUPLICATAS - ANO 2021
============================================================
📊 Distribuição das classificações:
_classificacao
unico              82403
compra_repetida     1083
duplicata_real       136
------------------------------------------------------------
============================================================
🗑️ REMOÇÃO DE DUPLICATAS REAIS - ANO 2021
============================================================
   Antes:     83,622 registros
   Depois:    83,486 registros
   Removidos: 136 (0.16%)
   Preservados como 'compra_repetida': 1,083
------------------------------------------------------------

############################################################
# PROCESSANDO ANO 2022
############################################################
============================================================
📌 ANÁLISE DE DUPLICATAS - ANO 2022
============================================================
Total de registros: 88,991

🔹 DUPLICATAS COMPLETAS (todas as colunas):
   Registros duplicados: 0 (0.00%)
   Registros únicos: 88,991

🔹 DUPLICATAS PARCIAIS (baseado em: ['descricao_catmat', 'fornecedor', 'preco_total', 'qtd_itens_comprados']):
   Registros com duplicatas parciais: 1,714 (1.93%)
   Número de grupos duplicados: 828

   Maiores grupos de duplicatas parciais (top 5):
      1. CEFTRIAXONA SÓDICA, CONCENTRAÇÃO:1 G, FORMA FARMACEUTICA:PÓ P/ SOLUÇÃO INJETÁVEL | PONTAMED FARMACEUTICA LTDA | 3700.0 | -> 4 registros
      2. FENITOÍNA SÓDICA, DOSAGEM:50 MG/ML, APRESENTAÇÃO:SOLUÇÃO INJETÁVEL | PONTAMED FARMACEUTICA LTDA | 257.6 | 100 -> 4 registros
      3. FITOMENADIONA, DOSAGEM:10 MG/ML, APRESENTAÇÃO:SOLUÇÃO INJETÁVEL | PONTAMED FARMACEUTICA LTDA | 201.6 | 100 -> 4 registros
      4. HIDROCORTISONA, COMPOSIÇÃO:SAL ACETATO, CONCENTRAÇÃO:10 MG/G, FORMA FARMACÊUTICA:CREME | LIDER MED LTDA | 134.2 | 20 -> 4 registros
      5. ALBUMINA HUMANA, CONCENTRAÇÃO:20%, USO:INJETÁVEL | RM DISTRIBUIDORA DE MEDICAMENTOS LTDA | 684000.0 | 6000 -> 3 registros

📊 RESUMO FASE 1:
   Total registros: 88,991
   Duplicatas completas: 0
   Duplicatas parciais: 1,714
------------------------------------------------------------
============================================================
🔍 DIAGNÓSTICO DOS GRUPOS - ANO 2022
============================================================
   📌 Total de grupos duplicados: 828
   📌 Mostrando os 3 maiores grupos:

------------------------------------------------------------
🔹 GRUPO #1 — 4 registros
   Chave: CEFTRIAXONA SÓDICA, CONCENTRAÇÃO:1 G, FORMA FARMAC | PONTAMED FARMACEUTICA LTDA | 3700.0 | 1000
                                                                descricao_catmat     compra   insercao   cnpj_instituicao codigo_br           nome_instituicao modalidade_compra
CEFTRIAXONA SÓDICA, CONCENTRAÇÃO:1 G, FORMA FARMACEUTICA:PÓ P/ SOLUÇÃO INJETÁVEL 2022-06-30 2023-04-17 76.205.640/0001-08    442701 MUNICIPIO DE DOIS VIZINHOS            Pregão
CEFTRIAXONA SÓDICA, CONCENTRAÇÃO:1 G, FORMA FARMACEUTICA:PÓ P/ SOLUÇÃO INJETÁVEL 2022-07-15 2023-11-13 76.205.640/0001-08    442701 MUNICIPIO DE DOIS VIZINHOS            Pregão
CEFTRIAXONA SÓDICA, CONCENTRAÇÃO:1 G, FORMA FARMACEUTICA:PÓ P/ SOLUÇÃO INJETÁVEL 2022-08-03 2023-02-15 76.205.640/0001-08    442701 MUNICIPIO DE DOIS VIZINHOS            Pregão
   💡 → COMPRA REPETIDA LEGÍTIMA (diferenças em: ['compra', 'insercao', 'cnpj_instituicao', 'nome_instituicao'])
------------------------------------------------------------
🔹 GRUPO #2 — 4 registros
   Chave: FENITOÍNA SÓDICA, DOSAGEM:50 MG/ML, APRESENTAÇÃO:S | PONTAMED FARMACEUTICA LTDA | 257.6 | 100
                                                  descricao_catmat     compra   insercao   cnpj_instituicao codigo_br               nome_instituicao modalidade_compra
FENITOÍNA SÓDICA, DOSAGEM:50 MG/ML, APRESENTAÇÃO:SOLUÇÃO INJETÁVEL 2022-07-28 2022-10-21 76.105.550/0001-37    267107       MUNICIPIO DE MANDIRITUBA            Pregão
FENITOÍNA SÓDICA, DOSAGEM:50 MG/ML, APRESENTAÇÃO:SOLUÇÃO INJETÁVEL 2022-08-11 2023-06-07 95.440.517/0001-08    267107 MUNICIPIO DE SANTA CRUZ DO SUL            Pregão
FENITOÍNA SÓDICA, DOSAGEM:50 MG/ML, APRESENTAÇÃO:SOLUÇÃO INJETÁVEL 2022-10-13 2023-01-06 46.634.291/0001-70    267107      MUNICIPIO DE ITAPETININGA            Pregão
   💡 → COMPRA REPETIDA LEGÍTIMA (diferenças em: ['compra', 'insercao', 'cnpj_instituicao', 'nome_instituicao'])
------------------------------------------------------------
🔹 GRUPO #3 — 4 registros
   Chave: FITOMENADIONA, DOSAGEM:10 MG/ML, APRESENTAÇÃO:SOLU | PONTAMED FARMACEUTICA LTDA | 201.6 | 100
                                               descricao_catmat     compra   insercao   cnpj_instituicao codigo_br                                          nome_instituicao modalidade_compra
FITOMENADIONA, DOSAGEM:10 MG/ML, APRESENTAÇÃO:SOLUÇÃO INJETÁVEL 2022-05-11 2022-05-23 10.505.599/0001-79    292399                    FUNDO MUNICIPAL DE SAUDE DE BALSA NOVA            Pregão
FITOMENADIONA, DOSAGEM:10 MG/ML, APRESENTAÇÃO:SOLUÇÃO INJETÁVEL 2022-05-11 2022-06-03 09.307.789/0001-00    292399                                  FUNDO MUNICIPAL DE SAUDE            Pregão
FITOMENADIONA, DOSAGEM:10 MG/ML, APRESENTAÇÃO:SOLUÇÃO INJETÁVEL 2022-06-23 2022-10-13 09.588.897/0001-90    292399 FUNDO MUNICIPAL DE SAUDE - MUNICIPIO DE NOVA TEBAS PARANA            Pregão
   💡 → COMPRA REPETIDA LEGÍTIMA (diferenças em: ['compra', 'insercao', 'cnpj_instituicao', 'nome_instituicao'])
------------------------------------------------------------
============================================================
🏷️ CLASSIFICAÇÃO DE DUPLICATAS - ANO 2022
============================================================
📊 Distribuição das classificações:
_classificacao
unico              87277
compra_repetida     1549
duplicata_real       165
------------------------------------------------------------
============================================================
🗑️ REMOÇÃO DE DUPLICATAS REAIS - ANO 2022
============================================================
   Antes:     88,991 registros
   Depois:    88,826 registros
   Removidos: 165 (0.19%)
   Preservados como 'compra_repetida': 1,549
------------------------------------------------------------

############################################################
# PROCESSANDO ANO 2023
############################################################
============================================================
📌 ANÁLISE DE DUPLICATAS - ANO 2023
============================================================
Total de registros: 31,992

🔹 DUPLICATAS COMPLETAS (todas as colunas):
   Registros duplicados: 0 (0.00%)
   Registros únicos: 31,992

🔹 DUPLICATAS PARCIAIS (baseado em: ['descricao_catmat', 'fornecedor', 'preco_total', 'qtd_itens_comprados']):
   Registros com duplicatas parciais: 906 (2.83%)
   Número de grupos duplicados: 452

   Maiores grupos de duplicatas parciais (top 5):
      1. ANLODIPINO BESILATO, DOSAGEM:5 MG | NF FARMACEUTICA E LOGISTICA LTDA | 240.0 | 8000 -> 3 registros
      2. ENALAPRIL MALEATO, DOSAGEM:10 MG | DISTRIBUIDORA DE MEDICAMENTOS BACKES LTDA | 750.0 | 15000 -> 3 registros
      3. ABAIXADOR LÍNGUA, MATERIAL:MADEIRA, TIPO:DESCARTÁVEL, COMPRIMENTO:14 CM, FORMATO:TIPO ESPÁTULA, EMBALAGEM INDIVIDUAL, LA -> 2 registros
      4. ACEBROFILINA, CONCENTRAÇÃO:10 MG/ML, FORMA FARMACEUTICA:XAROPE | HEALTH DISTRIBUIDORA DE MEDICAMENTOS LTDA | 10290.0 | 1 -> 2 registros
      5. ACEBROFILINA, CONCENTRAÇÃO:5 MG/ML, FORMA FARMACEUTICA:XAROPE | HEALTH DISTRIBUIDORA DE MEDICAMENTOS LTDA | 7860.0 | 150 -> 2 registros

📊 RESUMO FASE 1:
   Total registros: 31,992
   Duplicatas completas: 0
   Duplicatas parciais: 906
------------------------------------------------------------
============================================================
🔍 DIAGNÓSTICO DOS GRUPOS - ANO 2023
============================================================
   📌 Total de grupos duplicados: 452
   📌 Mostrando os 3 maiores grupos:

------------------------------------------------------------
🔹 GRUPO #1 — 3 registros
   Chave: ANLODIPINO BESILATO, DOSAGEM:5 MG | NF FARMACEUTICA E LOGISTICA LTDA | 240.0 | 8000
                 descricao_catmat     compra   insercao   cnpj_instituicao codigo_br                     nome_instituicao modalidade_compra
ANLODIPINO BESILATO, DOSAGEM:5 MG 2023-03-23 2023-08-01 63.762.009/0002-30    272434 MUNICIPIO DE NOVO HORIZONTE DO OESTE            Pregão
ANLODIPINO BESILATO, DOSAGEM:5 MG 2023-03-28 2024-01-19 11.811.613/0001-25    272434             FUNDO MUNICIPAL DE SAUDE            Pregão
ANLODIPINO BESILATO, DOSAGEM:5 MG 2023-11-30 2025-08-15 08.966.882/0001-56    272434             FUNDO MUNICIPAL DE SAUDE            Pregão

In [30]:
# ============================================
# CONCATENAÇÃO DAS BASES 2020-2026
# ============================================

def concatenar_bases(dataframes, anos, salvar_arquivo=None):
    """
    Concatena os DataFrames anuais tratados em um único DataFrame.
    A coluna 'ano_compra' (já presente em cada base) identifica a origem.
    
    Parâmetros:
        dataframes: dict {ano: DataFrame}
        anos: lista de anos a concatenar
        salvar_arquivo: (opcional) caminho para salvar o CSV resultante
    
    Retorna:
        df_consolidado (DataFrame único com todos os anos)
    """
    print("="*60)
    print("🔗 CONCATENAÇÃO DAS BASES 2020-2026")
    print("="*60)
    
    # FASE 1: Coletar apenas os anos existentes
    lista_dfs = []
    for ano in anos:
        if ano in dataframes:
            df = dataframes[ano]
            lista_dfs.append(df)
            print(f"   ✅ Ano {ano}: {len(df):,} registros | {df.shape[1]} colunas")
        else:
            print(f"   ⚠️ Ano {ano} não encontrado — pulando.")
    
    if not lista_dfs:
        print("❌ Nenhum DataFrame para concatenar.")
        return None
    
    # FASE 2: Concatenação (empilhamento vertical)
    print("\n📌 Concatenando...")
    df_consolidado = pd.concat(lista_dfs, ignore_index=True)
    
    # FASE 3: Resumo final
    print("\n" + "="*60)
    print("📊 RESULTADO DA CONCATENAÇÃO")
    print("="*60)
    print(f"   Total de registros: {len(df_consolidado):,}")
    print(f"   Total de colunas:   {df_consolidado.shape[1]}")
    print(f"\n   Distribuição por ano:")
    dist = df_consolidado['ano_compra'].value_counts().sort_index()
    for ano, qtd in dist.items():
        print(f"      {ano}: {qtd:,} registros")
    print("="*60)
    
    # FASE 4: Salvar (opcional)
    if salvar_arquivo:
        df_consolidado.to_csv(salvar_arquivo, index=False, encoding='utf-8')
        print(f"\n💾 Arquivo salvo em: {salvar_arquivo}")
    
    return df_consolidado

# ============================================
# EXECUÇÃO — CONCATENAR TODOS OS ANOS
# ============================================

anos = [2020, 2021, 2022, 2023, 2024, 2025, 2026]

df_consolidado = concatenar_bases(
    dataframes=dataframes,
    anos=anos,
    salvar_arquivo="dados_consolidados_BPS_2020_2026.csv"
)

============================================================
🔗 CONCATENAÇÃO DAS BASES 2020-2026
============================================================
   ✅ Ano 2020: 84,689 registros | 30 colunas
   ✅ Ano 2021: 83,486 registros | 30 colunas
   ✅ Ano 2022: 88,826 registros | 30 colunas
   ✅ Ano 2023: 31,940 registros | 30 colunas
   ✅ Ano 2024: 26,124 registros | 30 colunas
   ✅ Ano 2025: 26,167 registros | 30 colunas
   ✅ Ano 2026: 815 registros | 30 colunas

📌 Concatenando...

============================================================
📊 RESULTADO DA CONCATENAÇÃO
============================================================
   Total de registros: 342,047
   Total de colunas:   30

   Distribuição por ano:
      2020: 84,689 registros
      2021: 83,486 registros
      2022: 88,826 registros
      2023: 31,940 registros
      2024: 26,124 registros
      2025: 26,167 registros
      2026: 815 registros
============================================================

💾 Arquivo salvo em: dados_consolidados_BPS_2020_2026.csv

In [31]:
# 1. Confirmar shape geral
print("Shape:", df_consolidado.shape)

# 2. Verificar se todas as colunas vieram
print("\nColunas:", df_consolidado.columns.tolist())

# 3. Verificar nulos remanescentes
print("\nNulos por coluna (só >0):")
nulos = df_consolidado.isnull().sum()
print(nulos[nulos > 0].sort_values(ascending=False))

# 4. Espiar as primeiras e últimas linhas
print("\nPrimeiras linhas:")
print(df_consolidado.head(3).to_string())

print("\nÚltimas linhas:")
print(df_consolidado.tail(3).to_string())

# 5. Confirmar que a coluna 'ano_compra' está correta
print("\nRegistros por ano:")
print(df_consolidado['ano_compra'].value_counts().sort_index())

Shape: (342047, 30)

Colunas: ['ano_compra', 'nome_instituicao', 'esfera', 'cnpj_instituicao', 'municipio_instituicao', 'uf', 'compra', 'insercao', 'codigo_br', 'descricao_catmat', 'unidade_fornecimento', 'generico', 'anvisa', 'modalidade_compra', 'tipo_compra', 'capacidade', 'unidade_medida', 'unidade_fornecimento_capacidade', 'cnpj_fornecedor', 'fornecedor', 'cnpj_fabricante', 'fabricante', 'qtd_itens_comprados', 'preco_unitario', 'preco_total', 'mes_compra', 'dia_compra', 'ano_insercao', 'mes_insercao', 'dia_insercao']

Nulos por coluna (só >0):
capacidade                         217674
unidade_medida                     217674
anvisa                             171846
insercao                             2126
ano_insercao                         2126
mes_insercao                         2126
dia_insercao                         2126
nome_instituicao                      157
unidade_fornecimento                   25
unidade_fornecimento_capacidade        25
dtype: int64

Primeiras linhas:
   ano_compra                                     nome_instituicao     esfera    cnpj_instituicao municipio_instituicao  uf     compra   insercao codigo_br                                                                                 descricao_catmat unidade_fornecimento       generico        anvisa modalidade_compra     tipo_compra  capacidade unidade_medida unidade_fornecimento_capacidade     cnpj_fornecedor                  fornecedor     cnpj_fabricante                                          fabricante  qtd_itens_comprados  preco_unitario  preco_total  mes_compra  dia_compra  ano_insercao  mes_insercao  dia_insercao
0        2020               FUNDO  MUNICIPAL  DE  SAUDE DE  MARABA  MUNICIPAL  18.478.187/0001-07                MARABA  PA 2020-01-01 2024-01-19    270019                                 GLICONATO DE CÁLCIO, DOSAGEM:10%, APRESENTAÇÃO:SOLUÇÃO INJETÁVEL               AMPOLA              N  1.031100e+12            Pregão  ADMINISTRATIVA        10.0             ML                 AMPOLA 10.00 ML  04.949.905/0001-63        F CARDOSO E CIA LTDA  01.571.702/0001-98               HALEX ISTAR INDUSTRIA FARMACEUTICA SA                 9750           4.500      43875.0           1           1        2024.0           1.0          19.0
1        2020  FUNDO MUNICIPAL DE SAUDE - MUNICIPIO DE ALTO PARANA  MUNICIPAL  08.533.932/0001-01           ALTO PARANA  PR 2020-01-01 2020-03-13    243488  BOLSA VENTILAÇÃO PULMONAR, MATERIAL:BORRACHA, CAPACIDADE:1 L, APLICAÇÃO:VENTILAÇÃO / REINALAÇÃO              UNIDADE  Não Informado           NaN            Pregão  ADMINISTRATIVA         NaN            NaN                         UNIDADE  06.974.929/0001-06  NOROESTE MEDICAMENTOS LTDA  73.856.593/0001-66                         PRATI, DONADUZZI & CIA LTDA                    3           6.900         20.7           1           1        2020.0           3.0          13.0
2        2020                     MUNICIPIO DE AMERICO BRASILIENSE  MUNICIPAL  43.976.166/0001-50   AMERICO BRASILIENSE  SP 2020-01-01 2020-10-06    267567                                                                        CARVEDILOL, DOSAGEM:25 MG           COMPRIMIDO              N  1.014601e+12            Pregão  ADMINISTRATIVA         NaN            NaN                      COMPRIMIDO  01.140.868/0001-50      CIRURGICA OLIMPIO LTDA  61.150.447/0001-31  LABORATORIOS BALDACCI LTDA EM RECUPERACAO JUDICIAL                36000           0.155       5580.0           1           1        2020.0          10.0           6.0

Últimas linhas:
        ano_compra                            nome_instituicao    esfera    cnpj_instituicao municipio_instituicao  uf     compra   insercao codigo_br                                                                           descricao_catmat unidade_fornecimento generico        anvisa modalidade_compra     tipo_compra  capacidade unidade_medida unidade_fornecimento_capacidade     cnpj_fornecedor                                                                   fornecedor     cnpj_fabricante                                                 fabricante  qtd_itens_comprados  preco_unitario  preco_total  mes_compra  dia_compra  ano_insercao  mes_insercao  dia_insercao
342044        2026  FUNDO ESTADUAL DE SAUDE DO ESTADO DA BAHIA  ESTADUAL  05.816.630/0001-52              SALVADOR  BA 2026-03-05 2026-03-11    273474                             MILRINONA, DOSAGEM:1 MG/ML, TIPO MEDICAMENTO:SOLUÇÃO INJETÁVEL               FRASCO        S  1.746500e+12            Pregão  ADMINISTRATIVA        10.0             ML                 FRASCO 10.00 ML  96.827.563/0001-27                                                    MEDISIL MEDICAMENTOS LTDA  09.058.502/0001-48  FARMA VISION IMPORTACAO E EXPORTACAO DE MEDICAMENTOS LTDA                 3040           57.22     173948.8           3           5        2026.0           3.0          11.0
342045        2026  FUNDO ESTADUAL DE SAUDE DO ESTADO DA BAHIA  ESTADUAL  05.816.630/0001-52              SALVADOR  BA 2026-03-05 2026-03-11    280116                                                                 BOSENTANA, DOSAGEM:62,5 MG           COMPRIMIDO        S  1.235203e+12            Pregão  ADMINISTRATIVA         NaN            NaN                      COMPRIMIDO  15.145.035/0001-96  RIOBAHIAFARMA COMERCIO E DISTRIBUICAO DE PRODUTOS MEDICOS E COSMETICOS LTDA  73.663.650/0001-90                                  RANBAXY FARMACEUTICA LTDA                 3420           16.69      57079.8           3           5        2026.0           3.0          11.0
342046        2026  FUNDO ESTADUAL DE SAUDE DO ESTADO DA BAHIA  ESTADUAL  05.816.630/0001-52              SALVADOR  BA 2026-03-05 2026-03-11    352204  DEXMEDETOMIDINA CLORIDRATO, CONCENTRAÇAO:100 MCG/ML, FORMA FARMACEUTICA:SOLUÇÃO INJETÁVEL               FRASCO        N  1.049714e+12            Pregão  ADMINISTRATIVA         2.0             ML                  FRASCO 2.00 ML  60.665.981/0009-75                                      UNIAO QUIMICA FARMACEUTICA NACIONAL S A  60.665.981/0001-18                    UNIAO QUIMICA FARMACEUTICA NACIONAL S A               103550            5.60     579880.0           3           5        2026.0           3.0          11.0

Registros por ano:
ano_compra
2020    84689
2021    83486
2022    88826
2023    31940
2024    26124
2025    26167
2026      815
Name: count, dtype: int64

In [32]:
import gzip
import shutil

# Comprimir o CSV original SEM alterar nada
with open("dados_consolidados_BPS_2020_2026.csv", "rb") as f_in:
    with gzip.open("dados_consolidados_BPS_2020_2026.csv.gz", "wb", compresslevel=9) as f_out:
        shutil.copyfileobj(f_in, f_out)

# Verificar tamanho
import os
tam_original = os.path.getsize("dados_consolidados_BPS_2020_2026.csv") / 1024**2
tam_comprimido = os.path.getsize("dados_consolidados_BPS_2020_2026.csv.gz") / 1024**2

print("="*50)
print("📊 RELATÓRIO DE COMPRESSÃO")
print("="*50)
print(f"   CSV original:   {tam_original:.2f} MB")
print(f"   CSV.GZ:         {tam_comprimido:.2f} MB")
print(f"   Redução:        {(1 - tam_comprimido/tam_original)*100:.1f}%")
print("="*50)

==================================================
📊 RELATÓRIO DE COMPRESSÃO
==================================================
   CSV original:   138.41 MB
   CSV.GZ:         18.77 MB
   Redução:        86.4%
==================================================